### ISSUE TITLE
0001882:
add 'crm type' (panel?) to contacts

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1025]
**Reported by pschuele on 11 Nov 2009 16:09**

add &#039;crm type&#039; (panel?) to contacts

- CUSTOMER/PARTNER/RESPONSIBLE
- use that information when adding relations in crm edit dialog / filter

**Comment by pschuele** [comment]
no longer relevant

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Nov 2009 13:24**

+ use contact type to determine &#039;Responsible&#039; persons

we should postpone the implementation of the crm/relation type to the next (minor?) release because this needs more thinking/effort.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Aug 2015 13:34**

we could add a feature switch for this as we already implemented that for a customer.
