### ISSUE TITLE
0001888:
improve grid store handling

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1028]
**Reported by pschuele on 12 Nov 2009 10:49**

improve grid store handling
- don&#039;t reload the complete store if rows have been deleted
- do all (?) requests in the background and don&#039;t bother the user
- don&#039;t lose the selection when new data is added  to the store

**Comment by pschuele** [comment]
no longer relevant

**Comment by Gloirin** [comment]
Related to #2202
