### ISSUE TITLE
0001926:
Tool-Tip on any note disappaers too soon

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1046]
**Reported by bbalazs on 1 Dec 2009 12:23**

**Version:** August (2009-11) Beta 1

For longer notes not the whole text is displayed in the note-preview-panel on the right-hand-side. This is good, as it gives the user an overview of notes. The whole note is then displayed via a tool-tip. Unfortunatly this tool-tip disappears automatically after some time. This time is too short to read longer notes.

Better: have the tool-tip appear when the mouse rests on the note - and have it disappear only when the mouse moves again.

**Comment by pschuele** [comment]
no longer relevant
