### ISSUE TITLE
0001962:
Folders with DOTs (.) appear three times

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1064]
**Reported by DuncanConroy on 11 Dec 2009 10:39**

**Version:** August (2009-11-1)

I just upgraded to the new Version. My folders existed before the update.
Foldernames including a DOT appear three times.

For example I have the folder named &quot;tine20.org&quot;, I now get
- tine20
|--&gt;tine20.org
- tine20.org

I attached a screenshot.

When I click on the bottom folder, I get into that one marked in the screenshot, but not the other way around.

**Comment by pschuele** [comment]
i think that should no longer be an issue, as (all?) folder delimiters are quoted.

please reopen (or comment here), if that's still an issue.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Dec 2009 14:36**

could not reproduce this with dbmail.

i think it has something to do with the delimiter of your mailserver (it should be the &#039;.&#039;). i&#039;m not sure how we can fix this problem. perhaps we shouldn&#039;t allow delimiter chars in folder names?

**Comment by Gloirin** [comment]
**Comment posted by DuncanConroy on 12 Dec 2009 15:17**

Yeah, the dot is also the delimiter for folders.

I have folders called
.INBOX
.INBOX.Alternativaplatform.com

Maybe there&#039;s a possibility to mask the dots, or replace them with a special char.

My server is running postfix as MTA and dovecot as IMAP-server.
