### ISSUE TITLE
0002036:
Filtering addresses and leads by tags does does not eliminate all unwanted items

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1100]
**Reported by mynodeus on 5 Jan 2010 14:06**

**Version:** August (2009-11-2)

When searching for adresses with a specific tag, it sometimes happens
that adresses are included in the result list that do not contain the
specified tag. &quot;sometimes&quot; means that this problems occurs for some
of the tags we use. For these tags, the effect can be reproduced.
The same problem occurs when filtering leads by tag in the CRM 
application. (All these tags are adminstrator-defined, i.e. no user-defined
tags were used. The tags that we use include blanks, perhaps this
causes problems? In this case entering tags that include blanks
should be made impossible)

**Additional information:** Attached is an example searching in leads for the tag &quot;Branche Zeitschriften&quot;.
The search produces mostly correct results (yellow tags) and one
incorrect result (white tag: &quot;Branche Zeitungen&quot;)
Thanks for considering the problem.

**Comment by pschuele** [comment]
should be already fixed. if not, please reopen.
