### ISSUE TITLE
0002072:
think about adding subfolders to shared addressbooks/calendars/leads/...

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1118]
**Reported by pschuele on 6 Jan 2010 16:53**

think about adding subfolders to shared addressbooks/calendars/leads/...

- This is also relevant for managing files/documents
- subfolders should also be addable to personal containers

**Comment by pschuele** [comment]
subfolders are already possible in the Filemanager. i think, we can close this for the moment.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Jan 2011 11:22**

we have an interesting discussion about subfolders in the forum: http://www.tine20.org/forum/viewtopic.php?f=24&amp;t=5150
