### ISSUE TITLE
0002098:
Ldap virtual accounts as made by phamm (others)

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1131]
**Reported by scirocco on 15 Jan 2010 18:18**

**Version:** August (2009-11-4)

Right now many Ldap queries are hard-coded for posixaccount schema, it would be nice to override these assumptions somehow.

For instance, when logging into tine20 the default filter in library/Zend/Ldap.php is hard-coded to &quot;(&amp;(objectClass=posixAccount)(uid=%s))&quot; as is also the default for the zend framework, but could be overridden with accountFilterFormat.

A more generic approach, like dovecot, where you can map Ldap values to dovecot internal values, would be great. http://hg.dovecot.org/dovecot-1.2/file/e2ea80e1c239/doc/dovecot-ldap-example.conf

I have been using phamm for a front-end virtual hosting manager to postfix if you want to look at that project: http://phamm.org/ their schema is located here http://phamm.org/docs.php

**Additional information:** Tine 2.0 looks like a very interesting, fast moving project, and I hope I get to make use of it.

**Comment by pschuele** [comment]
tine20 already supports configuration of account and user filters, i think this might be obsolete.
if not, please comment here!

**Comment by Gloirin** [comment]
**Comment posted by scirocco on 15 Jan 2010 18:19**

I also talk about this in the forum: http://www.tine20.org/forum/viewtopic.php?f=8&amp;t=2256
