### ISSUE TITLE
0002112:
Option to split dates over several days

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1138]
**Reported by rokka on 19 Jan 2010 16:38**

**Version:** August (2009-11-4)

Let&#039;s say you have a date that lasts for a few days, e. g. from monday to thursday. Every day you&#039;re busy from 9-17h. At the moment, you would have to create a single calendar record for every day, because if you use monday as the start and thursday as the end date, Tine 2.0 would assume the date is going continuously. But you&#039;re not busy in the evening. So maybe a button would be helpful that would create the single records automatically when you just tell Tine 2.0 the start date and the end date.

**Comment by pschuele** [comment]
why not use an event series? closing this as it is already possible by using recurring events.
