### ISSUE TITLE
0002118:
Self Made User-Agent

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1141]
**Reported by Peterchen on 20 Jan 2010 08:43**

**Version:** August (2009-11) RC1

An Option for Administrators to set a User-Agent in the Email Options.
At this Point it&#039;s Harc codet to &quot;Tine 2.0 Email Client&quot;.

**Comment by pschuele** [comment]
don't think we'll implement that.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 17 Mar 2010 11:26**

only allow to set this in the config.inc.php and not in the gui
