### ISSUE TITLE
0002128:
Community-Plugins

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1146]
**Reported by Blackmore on 20 Jan 2010 14:43**

ein Plugin, mit dem ich meine Facebook, meinVZ, was weiß ich in Tine20 übernehmen kann, evtl auch mit Übernahme des Geburtstages in den Calender...

**Comment by pschuele** [comment]
hm, maybe just use csv? i don't thinks we'll implement something like this.
