### ISSUE TITLE
0002140:
at new window groups displayed

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1152]
**Reported by Blackmore on 21 Jan 2010 20:50**

at the window to add a contace - at the bottom is a dropdown menu to select the Group, where the contact will be saved - is it possible to show direkt own Groups - so i will not open the whole Menu with all groups...

**Comment by pschuele** [comment]
already implemented

**Comment by Gloirin** [comment]
Related to #1153
