### ISSUE TITLE
0002146:
Button to show only completed tasks/leads/etc.

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1155]
**Reported by rokka on 26 Jan 2010 08:18**

**Version:** August (2009-11-4)

Maybe a button that shows only the completed tasks/leads/etc. would make sense, because if you have a list full of tasks, it&#039;s hard to see which tasks are closed if the open ones are displayed, too.

**Comment by pschuele** [comment]
you should use the filters for that - and maybe add a favorite

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 26 Jan 2010 10:32**

perhaps we should remove the button and use a statzus filter in  the filter toolbar for this
