### ISSUE TITLE
0002156:
make it possible to disable actions if user hasn't a certain right

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1160]
**Reported by pschuele on 26 Jan 2010 16:27**

make it possible to disable actions if user hasn&#039;t a certain right:

at the moment, only container grants are used by the actionUpdater to disable/enable actions. it should be possible to use rights here as well.

**Additional information:** see CRM/MANAGE_LEADS (leads grid)

**Comment by pschuele** [comment]
no longer relevant / too unspecific

**Comment by Gloirin** [comment]
Related to #1113
