### ISSUE TITLE
0002164:
Use sophisticated extJS Grid Component

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1164]
**Reported by bbalazs on 28 Jan 2010 17:15**

**Version:** August (2009-11-4)

For all list-grids, please use the second component shown on the following page:
http://www.extjs.com/deploy/dev/examples/grid/grid-plugins.html

This is needed for improved mouse-only handling of all lists in Tine. Major change is a checkbox as first element to allow mouse only selection of multiple objects in a list.

**Comment by pschuele** [comment]
we no longer invest in obsolete extjs widgets

**Comment by Gloirin** [comment]
Related to #2527
