### ISSUE TITLE
0002188:
Optimize "Remove File"

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1176]
**Reported by bbalazs on 28 Jan 2010 18:40**

**Version:** August (2009-11-4)

-&gt; generalize this for UploadFile Grid

Remove the &quot;Remove Attachment&quot; (&quot;Anhang entfernen&quot;) Button. Add a remove-cross at the end of each row of the attachment grid with the same functionality.

**Comment by pschuele** [comment]
attachment widget has already been improved.
