### ISSUE TITLE
0002250:
allow update of folder cache in a convenient way

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1206]
**Reported by pschuele on 5 Feb 2010 11:07**

allow update of folder cache in a convenient way

- if folders have changed on email server, we need to update the tine folder cache

**Comment by pschuele** [comment]
no longer relevant

**Comment by Gloirin** [comment]
Related to #1539

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Mar 2010 10:55**

perhaps we could do this in an async service or every time the user logs in (in the background or in steps)

see http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=3286
