### ISSUE TITLE
0002314:
js errors with uzbl/webkit (Webkit-gtk 1.1.21)

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1238]
**Reported by pschuele on 19 Feb 2010 08:48**

js errors with uzbl/webkit (Webkit-gtk 1.1.21)

js error console:
--
TypeError: Result of expression &#039;navigator.userAgent.toLowerCase().match(/version\/(\d+\.\d)/)&#039; [null] is not an object. /library/ExtJS/ext-all-debug.js:2936
TypeError: Result of expression &#039;Ext.form.DateField&#039; [undefined] is not an object. /Tinebase/js/2010-03-ms1-1/tine-all-debug.js?1264070078:46
TypeError: Result of expression &#039;Locale&#039; [undefined] is not an object. /Tinebase/js/Locale/build/en-all-debug.js?1264070077:2

**Additional information:** http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=2290

**Comment by pschuele** [comment]
should be already solved
