### ISSUE TITLE
0002394:
improve mailing from addressbook

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1278]
**Reported by pschuele on 15 Mar 2010 15:01**

improve mailing from addressbook
- add to/cc/bcc selection
- make it possible to send mails to all contacts in filter (not only the first 50)

**Additional information:** http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=3026

**Comment by pschuele** [comment]
already implemented

**Comment by Gloirin** [comment]
Related to #1682
