### ISSUE TITLE
0002400:
problem when sending notifictions from user with german umlauts in name

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1281]
**Reported by pschuele on 16 Mar 2010 14:14**

problem when sending notifictions from user with german umlauts in name

- maybe a problem only on some shared hosting systems

**Additional information:** see http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=3298

**Comment by pschuele** [comment]
no longer relevant
