### ISSUE TITLE
0002580:
Protect critical directories, if accessible from the web

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1369]
**Reported by necrom0rb on 28 Apr 2010 12:02**

The user can set the paths to the following directories on his own:

- tmp
- logfile
- session
- caching

All of these directories should be protected against accessing them from the web, so the server should not deliver them to clients. this can be achieved by preventing apache/the web-server to do so:

&lt;Directory /var/www/tine-directory/tmp&gt;
                Order deny,allow
                deny from all
&lt;/Directory&gt;

If one of these directories/files is accessible through the web, the setup should not proceed for the sake of security.

Greetings,
Thomas

**Comment by pschuele** [comment]
should be done by the webserver (config), not the application. the official debian/ubuntu tine20 packages already take care of that.
