### ISSUE TITLE
0002630:
Selected calendar filter for device is not used in Active Sync

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1394]
**Reported by Canny on 15 May 2010 09:34**

**Version:** git master

If I assign a filter to a registered ActiveSync device instead of all events that match the filter criterias, only the events in my calendar are synched with the assigned device.

**Comment by pschuele** [comment]
should be already fixed. please comment, if not.
