### ISSUE TITLE
0002718:
Small Calendar - dont make "today" activate "Day"-view, when user has different view activated

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1438]
**Reported by bbalazs on 3 Jun 2010 15:38**

Clicking on &quot;Today&quot; in the small calender, makes the main view change to today in day-view mode. Please correct: only open today in the current view mode (e.g. go to this week). Only open today in day mode, when user actually clicks on the day today in the small calendar.

**Comment by pschuele** [comment]
first issue already solved. closing this - I would not change the way the small calendar works.
