### ISSUE TITLE
0002738:
LDAP - Successful auth but missing group causes login to fail

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1448]
**Reported by Gurney on 10 Jun 2010 07:47**

**Version:** git master

The LDAP configuration seems correct. According to the log, the authentification against the LDAP database succeeds.

But then I get the following stacktrace:
2010-06-04T05:13:09+00:00 DEBUG (7): Tinebase_Server_Json::_handleException::165 exception &#039;Tinebase_Exception_Record_
NotDefined&#039; with message &#039;Group not found.&#039; in /media/server/www/tine20/Tinebase/Group/Ldap.php:161
Stack trace:
#0 /media/server/www/tine20/Tinebase/User.php(357): Tinebase_Group_Ldap-&gt;getGroupByIdFromSyncBackend(&#039;1000&#039;)

My main user is properly located in the Users OU and has a group id mentionned in the group field of its entry.

But there is no such group id in the Groups OU of the LDAP database, which I guess results in the error above.

I think the proper behaviour would be to create the missing groups (and any other missing information) in the LDAP base if the auth succeeds, and then to replicate them into the SQL database.

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 10 Jun 2010 07:50**

Related forum thread:
http://www.tine20.org/forum/viewtopic.php?f=10&amp;t=3516&amp;p=14890

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 3 Aug 2010 12:06**

I don&#039;t think there&#039;s a link with bug #1470. It has nothing to do with IMAP authentication,  it is just a matter of what groups need to be populated into the LDAP database.

Tine expects some groups to be present, and if they aren&#039;t, the login process fails - though the authentication against the LDAP server is correct.

It may be related to the setup.php script:
php /media/server/www/tine20/setup.php --import_accounts

which doesn&#039;t populate the proper groups.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 5 Dec 2010 19:11**

I&#039;m unsure how to process with this problem.

 I tend not to fix this problem, as I think that the ldap directory is not correctly populated. I think the better solution would be to fix the directory and not to add more code to Tine 2.0 to handle broken directories.

But I&#039;m open for good arguments.

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 9 Dec 2010 10:13**

I&#039;ve thought about it and I think you&#039;re right.

I was expecting it to behave with LDAP just like it behaves with SQL (i.e. creating the groups in the database upon installation) but maybe that&#039;s because I&#039;m not an organisation user.

But I would recommend it to be documented in some tool tips when selecting the LDAP storage database.

**Comment by pschuele** [comment]
closing this - won't fix
