### ISSUE TITLE
0002748:
Improve layout for iPad/Safari

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1453]
**Reported by carmei on 13 Jun 2010 22:44**

**Version:** Mialena (2010-03)

Tine is actually not usable with an iPad. Of course - active sync works, but if you try to use the application with safari you can not scroll within the different frames. Example: If you select an email only a part of the whole information is shown in the assigned frame. I think the main problem or reason is that you are not able to scoll within each frame. I am not really shure if it is possible based on safari. Using safari 5 on osx 10.6 it works perfectly. If you use safari 5 you see &quot;Scrollbalken&quot; in each frame, using the iPad you see each frame without them. Normally the iPhone should work the same way and maybe shows the same results.

**Comment by pschuele** [comment]
should be already fixed by #6290
