### ISSUE TITLE
0002752:
LDAP Computer not working correctly (SAMBA)

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1455]
**Reported by miscs on 16 Jun 2010 18:25**

**Version:** Mialena (2010-03) RC 1

Migrate from egroupware 1.6 to tine 20. egw16 with ldap as backend and sambaadmin enabled to provide samba-authentication via ldap. with tine i am able to use the same ldap-tree for users and groups but unfortunately not for computers/samba-shares.

schema:
include /etc/ldap/schema/core.schema
include /etc/ldap/schema/cosine.schema
include /etc/ldap/schema/nis.schema
include /etc/ldap/schema/inetorgperson.schema
include /etc/ldap/schema/samba.schema
include /etc/ldap/schema/misc.schema

config:
&#039;samba&#039; =&gt; array(
         &#039;manageSAM&#039; =&gt; &#039;true&#039;,
         &#039;backend&#039;   =&gt; &#039;ldap&#039;,
         &#039;machineGroup&#039;  =&gt; &#039;machines&#039;,
         &#039;minMachineId&#039;  =&gt; 2000,
         &#039;maxMachineId&#039;  =&gt; 3000,
         &#039;sid&#039;           =&gt; &#039;S-1-5-21-402006010-YYYYYYYY-XXXXXXX&#039;,
         &#039;ldap&#039;      =&gt; array(
             &#039;machineDn&#039;     =&gt; &#039;someDN&#039;,
         ),
)

In view Admin-&gt;Computers I now see all user accounts (same as view Users) and not my Samba-Shares.

My ldap-tree looks like this:

dn: dc=domain,dc=com
....

dn: ou=users,dc=domain,dc=com
...

dn: ou=groups,dc=domain,dc=com
...

dn: cn=group1,ou=groups,dc=domain,dc=com
structuralObjectClass: posixGroup
..
memberUid: user1
memberUid: user2
...

dn: uid=user1,ou=users,dc=domain,dc=com
...
sambaLMPassword: 121241241241412412412412412412414
sambaNTPassword: 124124124124124124124124124124124
sambaPwdLastSet: 1232808402
sambaLogonTime: 2147483647
sambaLogoffTime: 2147483647
sambaKickoffTime: 2147483647
sambaPwdCanChange: 1232808402
sambaPwdMustChange: 2147483647
sambaSID: S-1-5-21-3079435537-YYYYYYYYY-XXXXXXXX-21010
sambaAcctFlags: [U          ]

dn: sambaDomainName=SAMBA1,dc=domain,dc=com
sambaDomainName: SAMBA1
sambaSID: S-1-5-21-3079435537-YYYYYYYYY-XXXXXXX
sambaAlgorithmicRidBase: 1000
objectClass: sambaDomain
sambaNextUserRid: 1000
structuralObjectClass: sambaDomain
.......

dn: ou=machines,dc=domain,dc=com
objectClass: organizationalUnit
ou: machines
.....

But actually there are no computers under ou=machines. With egw16 this ldap three works fine.

Thanks for investigating!

**Comment by pschuele** [comment]
won't fix this atm.
