### ISSUE TITLE
0002766:
Dates in following month aren't shown initially in month-view when selecting favourite search

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1462]
**Reported by rokka on 17 Jun 2010 10:51**

**Version:** Mialena (2010-03-3)

Switch to month view. When you select a saved search from you favourites list, dates that are in the next month (the first few days of the next month are shown in month-view) don&#039;t appear. Once you refresh the calendar, they do appear. This behaviour doesn&#039;t occur when selecting single or multiple calendars directly.

**Comment by pschuele** [comment]
works for me
