### ISSUE TITLE
0002814:
tine-import errors without 'name'-contents

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1485]
**Reported by chrmoeller on 11 Jul 2010 18:13**

**Version:** git master

In thunderbird werden Inhalte SPAM-verdächtiger mails teilweise nicht gezeigt bzw. nur auf Wunsch. Bei Wunsch werden diese Inhalte freigeschaltet. Dazu wird die Absende-email_Adresse in das Adressbuch aufgenommen, jedoch OHNE Namen und ohne weitere Angaben. Es sei denn, man macht sich die Mühe, diese Daten zu ergänzen.
Bei der Synchronisation führt das zu Import-Fehlern bei Tine, weil dort zwingend n_fileas und n_fn vorgeschrieben sind.

**Steps to reproduce:** thunderbird-Adressbucheintrag anlegen mit der SPAM-Funktion &#039;Inhalte anzeigen&#039;. Synchronisieren. Fehlerprotokoll von tine20 Mialena (nicht trunk)

**Additional information:** Ergänzt man in thunderbird die Einträge um einen Namen, wird einwandfrei nach tine importiert.
Anregung: Bei fehlendem Namen Ersatzinhalt generieren, z.B. = mail-Adresse oder von Sync ausnehmen.

**Comment by pschuele** [comment]
fields are no longer mandatory
