### ISSUE TITLE
0002874:
Posteingänge zusammenfügen

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1515]
**Reported by TimTaylor on 30 Jul 2010 09:41**

**Version:** Mialena (2010-03-4)

Wenn mehrere Email-Adressen per POP3 oder IMAP eingebunden werden, sollte die ActiveSync-Schnittstelle eine Synergy-Option bieten und die Posteingänge auf dem mobilen Gerät zusammenfügen.

**Comment by Gloirin** [comment]
Related to #1765

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 12 Nov 2010 20:02**

ähm, besser wäre es in meinen augen einen virtuellen wurzelordner zu nutzen, und dort die anderen konten einzubinden.

Ich finde das mischen der daten verschiedener konten immer nervig.

**Comment by pschuele** [comment]
bei android gibt's die option - denke nicht, dass tine20 da was tun sollte.
