### ISSUE TITLE
0002992:
fix Setup_Backend_AllTests

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1574]
**Reported by pschuele on 3 Sep 2010 19:16**

fix Setup_Backend_AllTests

-&gt;  there seems to be some unbuffered queries here, fix them!

**Additional information:** 1) Setup_Backend_Schema_TableTest::testEquals_001
Zend_Db_Statement_Exception: SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.

/opt/workspace/tinetrunk/tine20/library/Zend/Db/Statement/Pdo.php:238
/opt/workspace/tinetrunk/tine20/library/Zend/Db/Statement.php:284
/opt/workspace/tinetrunk/tine20/library/Zend/Db/Adapter/Abstract.php:468
/opt/workspace/tinetrunk/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php:238
/opt/workspace/tinetrunk/tine20/library/Zend/Db/Select.php:674
/opt/workspace/tinetrunk/tine20/Setup/Backend/Mysql.php:127

1) Setup_Backend_MysqlTest::testStringToFieldStatement_008
Zend_Db_Statement_Exception: SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.

/opt/workspace/tinetrunk/tine20/library/Zend/Db/Statement/Pdo.php:238
/opt/workspace/tinetrunk/tine20/library/Zend/Db/Statement.php:284
/opt/workspace/tinetrunk/tine20/library/Zend/Db/Adapter/Abstract.php:468
/opt/workspace/tinetrunk/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php:238
/opt/workspace/tinetrunk/tine20/library/Zend/Db/Select.php:674
/opt/workspace/tinetrunk/tine20/Setup/Backend/Mysql.php:127

**Comment by pschuele** [comment]
already fixed
