### ISSUE TITLE
0002996:
small Calendar / Address-book enhancements

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1576]
**Reported by Bassbauer on 6 Sep 2010 06:06**

**Version:** Mialena (2010-03-6)

it would be nice if the calendar / addressbook would have the following features:

Calendar
- WeekView, show only the short month name to allow smaller browser windows
- Holidays, it would be nice if we could import holidays from any website in the internet for all countrys in the world
- A Calendar Year View which uses the whole window would be nice as well

- Addressbook, if entered a Birthdate, create reccuring event with a small birthday cake icon etc.

btw: time zone localization with differing start of the weekday works great, changed it to egypt and now the week starts at sunday.

Hope its okay to collect ideas here,,

Bass

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 Sep 2010 10:40**

i think it would be better to create single tasks for each idea ... but those could be subtasks of this one (new relationship: child of #2996)

**Comment by pschuele** [comment]
most of the features have already been implemented and i think, there are already open issues for the others -> close
