### ISSUE TITLE
0003000:
Group e-mail

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1578]
**Reported by raghnall on 7 Sep 2010 06:40**

**Version:** git master

instead of having to select each member of a group individually, it would be better to select the group that all users are in. This could tie into the group management that is already in place for Tine Base or you could extend the Address Book application to allow groups.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 Sep 2010 10:36**

we are planning to add groups to the addressbook

**Comment by pschuele** [comment]
group integration is already implementd
