### ISSUE TITLE
0000132:
Permission managing for one specfic contact

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#160]
**Reported by Jason on 29 Jul 2008 19:36**

**Version:** 2008-summer-ms1

It is better to share each individual contact information to other users as sometimes we don&#039;t want share a group of contacts to others.

OR

Is it possible to drag-and-drop each contact item from one folder to another?

**Comment by pschuele** [comment]
drag and drop between containers is already possible - closing this.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 30 Jul 2008 05:11**

You can always add more personal or shared folders to give away rights only for a limited number of contacts.

Drag and Drop support will be added later.

**Comment by Gloirin** [comment]
**Comment posted by Jason on 30 Jul 2008 14:18**

Yes, I do know those functions you mentioned. However, sometimes, people may want to modify the permission on ONLY one  of those contacts in stead of a group of contacts.

For example, I have a &quot;friends&quot; address book under shared folder, there are 3 items(contacts) in &quot;friends&quot; address book, say A, B and C. And it shared to another user M.

One day, I change my mind, I don&#039;t want share contact B to user M, but to user N or even don&#039;t share it anymore.

What I have to do now?

1) Create another address book, say &quot;friends-2&quot; and share it user N.
2) Delete contact B from address book &quot;friends&quot;
3) Recreate contact B in address book &quot;friends-2&quot; or under &quot;My Contacts&quot; 

of course, with &quot;Drag and Drop&quot; support, step 2 and 3 will be simple. However, I&#039;d like see the function for this case as:

1) be able to modify the permission to individual contact
2 AND the system can automatically group the contacts based on their permission setting. (optional)

Regards,

Jason
