### ISSUE TITLE
0003082:
add a date filter for a number of day's

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1619]
**Reported by garbor on 5 Oct 2010 08:50**

**Version:** Mialena (2010-03-6)

Because the existing &quot;inside&quot; filters like week, month and year are depending on the current date, it would be nice to have a filter like &quot;inside the last 30 days&quot;.

**Comment by Gloirin** [comment]
**Comment posted by astintzing on 20 Mar 2012 15:39**

there should be &quot;relative filters&quot; like &quot;Today&quot;, &quot;Yesterday&quot; etc. which have on each day/month/week another absolute value

**Comment by pschuele** [comment]
we already implemented that
