### ISSUE TITLE
0003188:
Make autocomplete=off for login form configurable

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1672]
**Reported by kore on 21 Oct 2010 08:58**

**Version:** Mialena (2010-03-7)

It would nice to be able to easily turn off the autocomplete=off for the input fields in the login form, so that users with proper password managers are still able to use them.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 26 Oct 2010 16:32**

i&#039;m not sure if this is possible because the login-dialog does not use a form submit to send the login data.

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 13 Mar 2012 15:34**

3 solutions:

1: switch to submit
2: use a cookie :(
3: http://docs.sencha.com/ext-js/3-4/#!/api/Ext.form.BasicForm see standardSubmit

**Comment by Gloirin** [comment]
**Comment posted by astintzing on 12 Apr 2012 12:40**

works on chrome and firefox

**Comment by Gloirin** [comment]
**Comment posted by mokraemer on 28 Nov 2014 11:17**

do you have a patch or a line, where to change the annoying default behavior?

**Comment by pschuele** [comment]
no longer relevant, i suppose?
