### ISSUE TITLE
0003218:
The defined custom field size doesn't match the displayed fiield size

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1687]
**Reported by Vertex on 23 Oct 2010 14:50**

**Version:** Mialena (2010-03-7)

If you define a custom field e.g. customer no. with 6 digits, the displayed field will be as wide as the window - it looks not very nice.

**Comment by pschuele** [comment]
no going to fix this atm
