### ISSUE TITLE
0003222:
make it possible to forward attached mails

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1689]
**Reported by pschuele on 27 Oct 2010 08:52**

make it possible to forward attached mails

- enable action in display dialog
- pass part id to make sure original attachments are part of the message
- need to adopt Felamimail_Controller_Message::sendMessage/_createMailForSending/_addAttachments

**Comment by Gloirin** [comment]
Related to #1680

**Comment by pschuele** [comment]
already implemented
