### ISSUE TITLE
0003244:
query nominatim again with less params if no location could be found

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1700]
**Reported by pschuele on 29 Oct 2010 08:45**

query nominatim again with less params if no location could be found

**Additional information:** see http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=4492

**Comment by Gloirin** [comment]
Related to #1516

**Comment by pschuele** [comment]
i think, this is already implemented
