### ISSUE TITLE
0003248:
timestamp of new notes is not displayed

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1702]
**Reported by Vertex on 1 Nov 2010 17:19**

**Version:** Mialena (2010-03-7)

If you create a new note there is no timestamp on the right side of the note icon just a blank field. But when you now close the contact (edit) mask and open it again the timestamp appears at the right place. Picture enclosed.

**Comment by Gloirin** [comment]
Related to #520

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 1 Nov 2010 17:45**

this happens because the note is saved only when the record it belongs to is saved and thus a timestamp is created.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 1 Nov 2010 17:47**

the whole notes/history concept has to be redesigned

**Comment by pschuele** [comment]
I'm closing this as this will be fixed when the notes are refactored.
