### ISSUE TITLE
0003252:
Notes with adjustable timestamp

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1704]
**Reported by Vertex on 1 Nov 2010 17:52**

**Version:** Mialena (2010-03-7)

It would be nice to have the option to change date/time of creation, because there are often situations which makes it nessesary e.g. you had a business trip and back to office you want to make some notes about phone calls and meetings with the correct date. So if you create a new note, the edit window could display the current date/time as default and you would have the option to adjust it to your needs.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 4 Nov 2010 10:36**

i&#039;m not sure if we need this, but i&#039;m putting it to feature requests.

**Comment by pschuele** [comment]
i don't think that we'll implement that.
