### ISSUE TITLE
0003274:
Remove everything from database if an user is deleted

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1715]
**Reported by mmuehlfeld on 2 Nov 2010 22:13**

Currently if an user is deleted, his calendar(s), addressbooks, etc. stay in the database.

This finally this makes the database to a grave of old data over the time.

**Additional information:** http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=4524#p18430

**Comment by Gloirin** [comment]
**Comment posted by mmuehlfeld on 2 Nov 2010 22:14**

If this is implemented, remove user FAQ entry link to this feature request and change the FAQ.
http://www.tine20.org/wiki/index.php/FAQ#What_happens_with_calendars_of_deleted_users.3F

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 3 Nov 2010 09:01**

if user is deleted, there should open a dialog where the admin is asked what to do with the users addressbooks, calendars, etc -&gt; delete or give another user / make public (shared)

**Comment by pschuele** [comment]
this is already implemented: #837
