### ISSUE TITLE
0003290:
add email features like delivery receipts, read receipts, priority

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1723]
**Reported by splinter03 on 7 Nov 2010 21:50**

**Version:** Mialena (2010-03-7)

i think email features like delivery receipts, read receipts, priority, ... are very important for an modern email-client

**Comment by Gloirin** [comment]
Related to #1009

**Comment by Gloirin** [comment]
Related to #3040

**Comment by Gloirin** [comment]
**Comment posted by robert.lischke on 10 Nov 2010 11:20**

from a usability perspective these features would only clutter the interface (small space)

we already discussed the priority feature internally and believe this to be unnecessary since only the recipient can decide on the priority of an email

**Comment by pschuele** [comment]
closing this - see Roberts comment above.
