### ISSUE TITLE
0003310:
change the calendar in user settings (to shared calendar)

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1733]
**Reported by D0ubl3D on 11 Nov 2010 21:05**

**Version:** Mialena (2010-03-7)

Need to change in the user settings the calender entry from standard private calendar to a shared calender.

i write it in german also:

ich bin grad beim testen von Tine. Ich würde gerne wissen, ob die Möglichkeit besteht, die in der Usereigenschaften gesetzten Einträge für Standartkalender und Standartadressbuch zu ändern. Folgende Situation. Ich möchte gerne für verschiedene Städte Usergroups anlegen. Das funktioniert. Nun möchte ich, das wenn ein User einen Termin in dem eigens dafür angelegten gemeinsamen Kalender oder gemeinsamen Adressbuch einen Eintrag macht, er nicht erst das gemeinsame Adressbuch oder den gemeinsamen Kalender aussuchen muss, sondern das dieses automatisch für den Benutzer oder die Gruppe voreingestellt ist.

**Comment by pschuele** [comment]
already implemented
