### ISSUE TITLE
0003326:
click cancel in file select dlg should collapse attachment grid

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1740]
**Reported by pschuele on 12 Nov 2010 13:49**

**Version:** Neele (2010-11) Beta 1

click cancel in file select dlg should collapse attachment grid (but only if it was collapsed before)

**Steps to reproduce:** The [+ Add File] still behaves strange, when no file is added, eg.

in E-mail
1. Write New Message
2. Add File
3. Cancel

The lower attachment bar remains open, but should be closed, since no attachments were added.

**Comment by Gloirin** [comment]
Related to #1650

**Comment by pschuele** [comment]
no longer relevant - attachment widget has been redesigned
