### ISSUE TITLE
0003358:
think about adding clearTable + purgeDeletedRecords CLI functions to scheduler

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1756]
**Reported by pschuele on 18 Nov 2010 13:33**

think about adding clearTable + purgeDeletedRecords CLI functions to scheduler

- we should add a config option for setting the date of expiry of deleted records (use as purgeDeletedRecords param)

**Comment by Gloirin** [comment]
Related to #1735

**Comment by pschuele** [comment]
already implemented
