### ISSUE TITLE
0003394:
add Tinebase_Controller unittests

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1774]
**Reported by lkneschke on 24 Nov 2010 09:45**

**Version:** git master

We have no unitests for Tinebase_Controller. We should add them.

- login/logout
- authentication
- expired/blocked users
- session destroyed?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 14 Dec 2010 14:15**

added first version ... but sadly it does not work as part of the Tinebase_AllTests suite atm

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Dec 2010 09:45**

postpone this to a future release with a newer version of phpunit (tried it with 3.4.5-1).

**Comment by pschuele** [comment]
no longer relevant
