### ISSUE TITLE
0003428:
Async tasks logging into DB

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1791]
**Reported by ketzaldev on 4 Dec 2010 18:35**

**Version:** Mialena (2010-03-7)

I would like to ask for a modification about Asynchronous tasks:
Each time an async tasks is triggered, there is a new log entry in the database, during this execution:
$job = Tinebase_AsyncJob::getInstance()-&gt;finishJob($job);

When using a cronjob, every minutes for mails, it&#039;s increasing seriously the DB (1MB more per week, 10000 new lines) --&gt;&gt; because there are too much log, it&#039;s become une information not that pertinent
I commented the line, but I don&#039;t know if the workaround is good?

Could you put this logging action into a test like &quot;if (Tinebase_Core::isLogLevel(Zend_Log::DEBUG))&quot; ?

Thanks

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 6 Dec 2010 09:33**

i suppose to add this table to clearable tables (see #2924 / http://www.tine20.org/wiki/index.php/CLI_Functions#Tinebase.clearTable )

**Comment by pschuele** [comment]
already refactored
