### ISSUE TITLE
0003448:
Link in Email einfügen

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1801]
**Reported by splinter03 on 7 Dec 2010 18:02**

**Version:** Mialena (2010-03-9)

Wenn man einen Link ein eine Email einfügen möchte, muss man erst einen Text markieren, und kann erst dann über den Link-Button einen Link erstellen. Markiert man keinen Text, erstellt er keinen Link.

Wenn man den Link-Einfügen Button bestätigt, ohne einen Text auszuwählen, sollte der Editor den Link als Text verwenden.

Dazu der Beitrag im Forum: http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=4998

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 8 Dec 2010 10:19**

welchen browser verwendest du?

**Comment by Gloirin** [comment]
**Comment posted by splinter03 on 8 Dec 2010 11:23**

Getestet mit Firefox 3.6.6 sowie Firefox 4 Beta 7
Hab auch mal in den Quelltext der Mail geschaut (nachdem ich einen Link einfügen wollte), der bleibt jedoch unverändert...

**Comment by Gloirin** [comment]
**Comment posted by robert.lischke on 8 Dec 2010 11:31**

Ich arbeite unter Linux/Ubuntu 10.10 und teste auf dem aktuellen Playground.

Mit &quot;Firefox 3.6.12&quot; tritt das geschilderte Problem auf.

Mit &quot;Google Chrome 9.0.597.10 dev&quot; kann ich das Problem nicht nachstellen.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 8 Dec 2010 11:38**

ok also ein FF bug, ich schieb den task mal auf die beta2 version, dann schauen wir uns das mal an.

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 8 Dec 2010 11:52**

mhmm ist in typo3 genau so - ist auch der gleiche editor.
aber in t3 werden urls automatisch in links umgewandelt, nachdem man enter oder [space] drückt.-

**Comment by pschuele** [comment]
ist eine dublette - wir haben bereits issues für url-handling im Felamimail:
#1667 + #1668
