### ISSUE TITLE
0003524:
Wording in filters

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1839]
**Reported by robert.lischke on 17 Dec 2010 10:05**

**Version:** git master

Work on wording in filter
especially get rid of double negative

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 17 Dec 2010 10:36**

and find a way to fix some german translations,

for example:

&quot;Kalender _eines von_ Meine Kalender&quot;

and in the selection widget:
&quot;Wählen Sie eine Kalender&quot;
&quot;Ausgewählt Kalender&quot;

**Comment by pschuele** [comment]
implemented and/or no longer relevant
