### ISSUE TITLE
0003564:
replace Tine.widgets.grid.QuickaddGridPanel with normal Tine.widgets.grid.GridPanel

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1859]
**Reported by pschuele on 22 Dec 2010 15:06**

replace Tine.widgets.grid.QuickaddGridPanel with normal Tine.widgets.grid.GridPanel + quickadd config

it is used in Admin/user edit dialog + Crm/Admin panel

**Comment by pschuele** [comment]
no longer relevant
