### ISSUE TITLE
0003574:
show 'changes' icon + history in grid

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1864]
**Reported by pschuele on 23 Dec 2010 15:16**

show &#039;changes&#039; icon + history in grid

**Additional information:** rule in german:

Änderungen durch andere Anwender, die in eine Ansicht einfließen, ohne expliziten Refresh durch den Anwender, werden in einer Änderungshistorie zusammengeführt, die der Nutzer durch den Click auf ein kleines Icon einsehen kann. Das Entfernen des Elements aus der Ansicht wird durch einen visuellen Effekt unterstützt.

**Comment by Gloirin** [comment]
Related to #1808

**Comment by pschuele** [comment]
no longer relevant
