### ISSUE TITLE
0003582:
improve filter selection (multiple calendars/folders)

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1868]
**Reported by pschuele on 27 Dec 2010 09:26**

improve filter selection (multiple calendars/folders)

- it is difficult to understand the way that more calendars are added to the &#039;in&#039; selection

see http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=5044

**Comment by Gloirin** [comment]
**Comment posted by htietze on 30 Sep 2013 08:53**

This issue relates to the n-out-of-m selection (https://www.tine20.org/wiki/index.php/Viewingn_of_m_selection) and concerns all &#039;one of&#039; relations.

The idea of multiple selection is easy to comprehend with drop-down controls that are applied as inline control of a larger, expandable table. But it&#039;s pretty hard to understand for one drop-down. To indicate the difference it&#039;s recommended to show an edit control with a &#039;plus&#039; button (blue in the styleguide page). 

The particular dialog can be improved with a more informative description, perhaps &#039;Add one more calendar to the selection list&#039;. And after the operation is done it would be good to show this label again (currently one needs to select an item from the lower list).

BTW: Many items may have a &#039;one of&#039; relation but do not provide selection support. For instance [City] [one of] and I assume the edit control wants a comma delimited string like [Berlin, Hamburg, Cologne] but nothing happens. I suggest to remove the &#039;one of&#039; option.

**Comment by pschuele** [comment]
closing this for the moment - but should be considered when the selection widgets are redesigned / refactored
