### ISSUE TITLE
0003586:
translations in some dialogs need to be fixed

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1870]
**Reported by pschuele on 27 Dec 2010 09:30**

translations in some dialogs need to be fixed

for example (in german) in the filter toolbar / calendar selection:

&quot;Ausgewählt Kalender&quot;
&quot;Wählen Sie eine Kalender&quot;

see http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=5044

**Comment by pschuele** [comment]
already fixed
