### ISSUE TITLE
0003650:
use correct regexps for email and urls

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1901]
**Reported by pschuele on 5 Jan 2011 13:03**

use correct regexps for email and urls in php

see http://en.wikipedia.org/wiki/Internationalizing_Domain_Names_in_Applications

perhaps we could use http://en.wikipedia.org/wiki/Internationalizing_Domain_Names_in_Applications for emails on the server

another idea: replace \w with something like that : [^\s:;]

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 5 Jan 2011 16:17**

js regexps already fixed (see Tinebase/js/extFixes.js)

**Comment by pschuele** [comment]
already implemented
