### ISSUE TITLE
0003706:
Handling users and groups (during selection or invitation)

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1929]
**Reported by robert.lischke on 10 Jan 2011 14:54**

**Version:** git master

german quote from Conny:

&quot;Wenn man eine Gruppe einlädt, werden (nach dem speichern) alle Gruppenmitglieder als &quot;Gruppen-Mitglied&quot; Teilnehmer angezeigt. Schöner währe wenn man die schon vor dem Speichern sehen könnte, und evtl. sogar welche davon entfernen könnte. Dann bleibt natürlich die Frage ob es dann noch eine Gruppeneinladung ist...&quot;

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 23 Jun 2017 14:42**

it&#039;s should not be possible to remove a groupmember for now

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 23 Jun 2017 19:35**

http://gerrit.tine20.com/customers/4944

**Comment by pschuele** [comment]
implemented
