### ISSUE TITLE
0000222:
Validation on post code(zip code)

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#204]
**Reported by Jason on 6 Aug 2008 22:24**

**Version:** 2008-summer-ms1-2

I found the system can accept the input data of inconsistent actual address and post(zip) code.

For example,

The address shows one place whereas the post(zip) does not belong to this area. And I found the Google map followed the address instead of the post(zip) code.

**Comment by pschuele** [comment]
if nominatim is configured - the address data is adjusted to the correct values

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 7 Aug 2008 09:42**

validation of addresses could only be done using external api&#039;s and is a legal ishue if this apis are allowed to be used.

some time ago i found a global geo-validation api, but i lost the link :-(

If you know such a service / api which could legally be used, please let me know

**Comment by Gloirin** [comment]
**Comment posted by hanshartl on 29 Jul 2012 16:47**

maybe not a full validation of address, but just a match between postal code and location, or type in postal code and location gets filled automatically.

Data available here:
http://www.geonames.org/export/
