### ISSUE TITLE
0004346:
[exim] Fehler beim weiterleiten von Emails mit Anhängen

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2241]
**Reported by trogel on 18 May 2011 07:07**

**Version:** Neele (2011-01-5)

Beim weiterleiten von EMails mit Anhängen werden diese &quot;geschrottet&quot;.
Beschrieben ist es hier:

 http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=7242

Als Vermutung steht im Raum, das dies nur beim Cyrus IMAP passiert.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 May 2011 11:47**

habe das eben mit dem gleichen cyrus und tine version 2011-01-4 ausprobiert und es hat mit pdf und mit jpg anhang funktioniert.

kannst du mir mal eine solche mail schicken? am besten aus dem thunderbird als .eml speichern (das original und die weitergeleitete nachricht).
meine email: p.schuele ät metaways.de

**Comment by Gloirin** [comment]
**Comment posted by trogel on 18 May 2011 12:48**

Habe eine Mail gesendet. Ich bin leicht angeschlagen und hoffe das ist nur bei mir eine Einstellungssache.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 20 May 2011 14:46**

ah, ich vermute, es gibt auf deinem system ein problem mit den zeilenumbrüchen. in der weitergeleiteten mail sind überall leerzeilen drin. merkwürdig. jetzt müssten wir herausfinden, wo diese zeilenumbrüche herkommen.

welche php version läuft bei dir?
kannst du mal das loglevel auf TRACE stellen und mir das log vom forwarden der mail senden?

**Comment by Gloirin** [comment]
**Comment posted by trogel on 24 May 2011 08:21**

Mail mit dem Log ist raus.

PHP läuft in Version 5.3.3-7. Vielleicht noch als Hintergrund: die Tine läuft auf einem Debian 6.0 auf einem eigenem Rechner. Datenbank, SMTP und IMAP laufen auf einem anderen Rechner und zwar hier unter Debian 5.0.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 6 Jun 2011 12:40**

welcher smtp server ist das denn bei euch?

man müsste nochmal genau herausfinden, an welcher stelle die mail geschrottet wird. beim senden an sich sah ja alles soweit gut aus.

ist die mail im &#039;Sent&#039;-ordner auch kaputt?

**Comment by Gloirin** [comment]
**Comment posted by trogel on 9 Jun 2011 06:19**

Bei uns kommt der Exim (Version 4.69)zum Einsatz.

Die Mail im Sent-Ordner sieht noch richtig gut aus, sobald ich die empfange ist es aber &quot;geschrottet&quot;.

**Comment by Gloirin** [comment]
**Comment posted by trogel on 9 Jun 2011 06:45**

Hab mir den Spaß gemacht und direkt im Betriebssystem in die Dateien geschaut. Also so wie es dort liegt, so zeigts auch die Tine an. Im Sent-order alles gut, bei der Inbox viele Leerzeichen.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 9 Jun 2011 08:32**

kannst du mir mal die beiden mails (aus sent + inbox) zuschicken? dann machen wir den vergleich.

scheinbar dupliziert der exim die linebreaks. evtl senden wir da die falschen. mal gucken!

**Comment by Gloirin** [comment]
**Comment posted by trogel on 9 Jun 2011 09:56**

Dateien sind gesendet.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 9 Jun 2011 09:57**

vielen dank!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Jun 2011 15:46**

bitte mal mit Maischa (2011-05-1) testen, ob das problem noch besteht.

**Comment by Gloirin** [comment]
**Comment posted by trogel on 23 Jun 2011 05:41**

Hatte die Idee gestern auch schon. :-) Habe Maischa (2011-05-11) gestern installiert aber das Problem besteht weiterhin.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 27 Jun 2011 12:25**

schade, das wäre eine einfache lösung gewesen. ;)

eventuell könnten wir noch etwas durch mitschneiden des datenverkehrs herausfinden. also mit tcpdump oder wireshark den (unverschlüsselten) datenstrom beim versenden mitschneiden und am besten wieder an mich per mail schicken.

**Comment by Gloirin** [comment]
**Comment posted by trogel on 29 Jun 2011 07:44**

Gesniffert habe ich noch nicht, aber mich in den Exim ein wenig eingelesen. Da gibts eine Option namens use_crlf:

 http://www.exim.org/exim-html-4.50/doc/html/spec_26.html#IX2061

Beschrieben wirds auch nochmal hier:

 http://php.net/manual/de/function.mail.php

Ich muß bloß die Zeit finden, die Option am Exim zu aktivieren. Vermutlich irgendwann nachts, wenn alle Mitarbeiter an der Matratze horchen. ;-)

**Comment by Gloirin** [comment]
**Comment posted by trogel on 29 Jun 2011 15:10**

Habe das Trace an Ihre Mailadresse gesendet.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Jul 2011 08:56**

habe mir das trace und die beiden files angeschaut.

im trace sieht man, dass schon beim senden die zusätzlichen leerzeilen eingebaut werden. auch in der email im sent folder sind sie schon drin. d.h. vermutlich geht das holen der ursprünglichen nachricht (bzw. das verarbeiten + ankleben) danach schief.

wenn sie mir noch einmal den (IMAP) trace beim versenden schicken könnten?

edit: konnten sie es mit dem exim flag testen?

**Comment by Gloirin** [comment]
**Comment posted by trogel on 13 Jul 2011 12:00**

Trace ist raus. Flag muß ich noch testen.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 20 Jul 2011 08:48**

hallo,

leider konnte ich auch in den ausführlichen traces das problem nicht lokalisieren.

könnten sie mir einen imap+smtp zugang einrichten? dann könnte ich versuchen, das problem damit zu reproduzieren.

**Comment by Gloirin** [comment]
**Comment posted by trogel on 21 Jul 2011 08:50**

Hmmn, ja wäre möglich. Das klären wir aber lieber per Mail. :-)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 26 Jul 2011 10:53**

wartet auf mailserver zugangsdaten fürs debuggen.

**Comment by Gloirin** [comment]
**Comment posted by trogel on 26 Jul 2011 11:16**

Ist raus.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Aug 2011 15:25**

ich glaube, ich habe das problem gelöst. es war ein \r zu viel an der falschen stelle .... 

@trogel + @kay:
bitte probiert mal die angehängte datei aus (Felamimail/Controller/Message.php) und sagt bescheid, ob es jetzt tut.

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 11 Aug 2011 16:53**

+1 super bei mir klapp es wie erwartet ;) - kommt das in das nächste release?

**Comment by Gloirin** [comment]
**Comment posted by trogel on 12 Aug 2011 05:54**

Yieeehaaaa, es klappt. Das ist eine riesige Erleichterung. :-)

Vielen Dank und einen zusätzlichen Gruß nach FTL.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 12 Aug 2011 11:18**

versuchen, da noch eine geschicktere lösung zu finden und das in Zend_Mime_Part einzubauen.

der endgültige fix wird dann ins nächste Maischa service release (2011-05-4) einfliessen (und natürlich auch in Milan).

edit: was ist denn FTL? ;)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 12 Aug 2011 15:16**

the problem should be finally fixed by adding a stream filter to Zend_mail_Mime that replaces \r\n with \n in non-encoded (or 7bit/8bit) mail parts.

**Comment by Trogel** [comment]
> Reported by trogel on 18 May 2011 07:07

Wherever trogel reported this issue, this is not me. My name is Trogel with a capital T. However, thanks for solving the problem!  :-)

**Comment by pschuele** [comment]
@Trogel sorry for the spam :blush:
