### ISSUE TITLE
0004400:
'from' sieve filter rule does not correctly match the name part of the header

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2268]
**Reported by pschuele on 25 May 2011 19:20**

**Version:** Maischa (2011-05) Beta 1

&#039;from&#039; sieve filter rule does not correctly match the name part of the header

-&gt; it only matches the email address

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 26 May 2011 10:16**

clarified the rule label.

from/to rule filters just check the email address and not the name part. if you want to add a filter rule for the sender name, you have to use the &quot;Header&quot; filter (with &quot;From&quot;).

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 26 May 2011 10:18**

see http://tools.ietf.org/html/rfc5228#section-2.7.4

**Comment by dimir** [comment]
I think it's not even possible with the "header"/"from" filter.
