### ISSUE TITLE
0004648:
empty mails sent by outlook and other email clients

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2383]
**Reported by pschuele on 26 Jul 2011 08:55**

**Version:** Maischa (2011-05-1)

empty mails sent by outlook and other email clients

**Additional information:** see http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=8818

**Comment by Gloirin** [comment]
Related to #2241

**Comment by Gloirin** [comment]
Related to #2492

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 26 Jul 2011 10:51**

perhaps there is a relation to #4346 where duplicate linebreaks seem to be the problem. we need to do some more debugging.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 5 Oct 2011 15:12**

looks like the problem is still there ...

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Dec 2011 19:46**

waiting for test-email from Pancho Villa

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Dec 2011 19:48**

@melo: can you confirm that the problem is still there in Maischa 2011-05-5?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Jan 2012 20:40**

please reopen if the problem persists.

**Comment by melo** [comment]
Hi, I'm not sure why you mentioned @melo on this, I didn't request this, nor did I report any problem. I'm not a Tine user...

Thanks,

**Comment by pschuele** [comment]
@melo sorry about that mention notification - we migrated the issues from mantis (which had a "melo" user) ...
