### ISSUE TITLE
0000344:
Implement Mobile Client

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#265]
**Reported by cweiss on 10 Sep 2008 09:07**

- start with general service
- add tasks

**Comment by Gloirin** [comment]
**Comment posted by anonymous on 23 May 2013 08:49**

Tine2.0 already have mobile clients now.

It support activesync and caldav ,so all the activesync and caldav client is the client of tine20.

Another, tine20 can develop a &quot;Responsive template&quot; for mobile(for example android phone,pad,etc...),

**Comment by pschuele** [comment]
we already improved the usability on touch devices (see #6290). i would close this for the moment.
