### ISSUE TITLE
0000474:
caching of reflection

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#329]
**Reported by pschuele on 16 Oct 2008 14:18**

caching of reflection and check if only needed application classes are loaded

**Comment by pschuele** [comment]
imho no longer relevant

**Comment by Gloirin** [comment]
Related to #401

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 24 Apr 2009 08:01**

ZF 1.7 comes with Zend_Json_Server_Cache
-&gt; we postpone this taks after ZF 1.7 migration
