### ISSUE TITLE
0000562:
refactor setFromJson/recordToJson functions

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#372]
**Reported by pschuele on 11 Nov 2008 11:05**

refactor setFromJson/recordToJson functions:
 
- where should we put these?
- implement abstract/generic functions (with relation-management)

**Comment by pschuele** [comment]
no longer relevant

**Comment by Gloirin** [comment]
Related to #378

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 27 Nov 2008 13:02**

we should put all these functions in the record and recordset
