### ISSUE TITLE
CRM: Web UI "this.endingLeadStateIds is undefined"

### ISSUE THREAD

**Issue by chrsch** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#41]
Infos
- Tine version: 2018.02.2
- Apache/2.4.18 (Ubuntu)
- PHP 7.0.28-0ubuntu0.16.04.1
- Browser: Firefox 59.0.2

Steps to reproduce
1. Start with a brand new installation
2. Add a new lead. Only fill in customer contact and name of the lead. Leave everything else blank
3. Save the lead to personal lead list

Expected result:
The lead is listed in the personal lead list of crm module

Observed result:
The list never finishes loading due to a javascript error visible in the browser console:
`TypeError: this.endingLeadStateIds is undefined[Learn More] index.php:1:3226412
	getViewRowClass https://tine.mydomain.com/index.php:1:3226412
	getViewRowClass self-hosted:997:17
	doRender https://tine.mydomain.com/library/ExtJS/ext-all.js:15:119942
	renderRows https://tine.mydomain.com/library/ExtJS/ext-all.js:15:128820
	renderBody https://tine.mydomain.com/library/ExtJS/ext-all.js:15:128876
	refresh https://tine.mydomain.com/library/ExtJS/ext-all.js:15:129287
	onDataChange https://tine.mydomain.com/library/ExtJS/ext-all.js:15:133287
	fire https://tine.mydomain.com/library/ExtJS/ext-all.js:7:22129
	fireEvent https://tine.mydomain.com/library/ExtJS/ext-all.js:7:19355
	loadRecords https://tine.mydomain.com/library/ExtJS/ext-all.js:7:286380
	createInterceptor/< https://tine.mydomain.com/library/ExtJS/adapter/ext/ext-base.js:7:5500
	success https://tine.mydomain.com/index.php:1:564150
	success https://tine.mydomain.com/index.php:1:565030
	initAjax/< https://tine.mydomain.com/index.php:1:1134629
	fire https://tine.mydomain.com/library/ExtJS/ext-all.js:7:22129
	fireEvent https://tine.mydomain.com/library/ExtJS/ext-all.js:7:19355
	handleResponse https://tine.mydomain.com/library/ExtJS/ext-all.js:7:78639
	f https://tine.mydomain.com/library/ExtJS/adapter/ext/ext-base.js:7:19646
	m/r[u]< https://tine.mydomain.com/library/ExtJS/adapter/ext/ext-base.js:7:20257

`

**Comment by msphn** [comment]
Cheers, we already resolved this issue. Tomorrow we'll release an updated package.

**Comment by pschuele** [comment]
fixed by https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/commit/fba07c80914f2d338459671f8dc492634774bb82

see also https://forge.tine20.org/view.php?id=13812
