### ISSUE TITLE
Nach Update auf 2018.02.03 Community kein Favicon

### ISSUE THREAD

**Issue by koelschejung74** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#42]
Hallo,

ich hoffe, ich bin hier richtig.

Ich habe heute via Ubuntu Repo auf die aktuelle Version aktualisiert, seit dem fehlt bei mir das favicon von tine 2.0.

Zu Testzwecken habe ich in meiner DEV Umgebung Tine ganz normal heruntergeladen und installiert. Auch dort das gleiche Verhalten.

Es ist kein Blocker, aber eine Unschönheit ;-).

Liebe Grüße
Uli

**Comment by pschuele** [comment]
hi Uli,
ja, du bist richtig - wir sind dran und fixen das bis zum nächsten release.

**Comment by pschuele** [comment]
still not working in current release 2018.02.4 :cry:

**Comment by corneliusweiss** [comment]
you need to check you rewrite rules. the correct rules should be in the debian/ubuntu packages

**Comment by pschuele** [comment]
the rewrite rule seems to be missing from the deb packages. i'll fix that.

**Comment by koelschejung74** [comment]
Ich habe meine DEV nun via all in one package manuell aktualisiert.

Im FF wird mir das Favicon angezeigt, im Chrome nicht, Cache habe ich gelöscht. Wenn sich was bei den RewriteRules sich geändert hat, was hat sich geändert?

Viele Grüße
Uli

**Comment by pschuele** [comment]
hier die routing configs:

nginx:
```nginxconf
      if (!-e $request_filename) { rewrite ^/.*$ /index.php?doRouting=1 last; }
```
apache:

```apacheconf
      <Location />
        RewriteCond %{REQUEST_FILENAME} -s [OR]
        RewriteCond %{REQUEST_FILENAME} -l [OR]
        RewriteCond %{REQUEST_FILENAME} -d
        RewriteRule ^.*$ - [NC,L]
        RewriteRule ^.*$ /index.php?doRouting=1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
     </Location>
```

ggf. müssen die pfade entsprechend angepasst werden.

**Comment by koelschejung74** [comment]
Hallo,

vielen Dank, funktioniert nun auch auf der Prod, die noch nicht aktualisiert wurde.

Viele Grüße
Uli

**Comment by koelschejung74** [comment]
Noch eine kleine Info, das Tine Zeichen in der alten Version ist mit dem alten Version da, aber das Copyright Symbol nicht ,-)

**Comment by pschuele** [comment]
hm, ich sehe das ® im titel in der 2018.02.4. welche version meinst du jetzt genau?

**Comment by koelschejung74** [comment]
Ich hatte nur infomieren wollen, das in der 02.03 Version das tine Zeichen mit den Rewrite enthalten ist, aber nicht das CopyRight. 

Habe nun aktualisiert, alles gut.

Vielen Dank

**Comment by koelschejung74** [comment]
Guten Morgen,

kann es sein, dass diese Redirect nur funktionieren, wenn das DocumentRoot direkt aufs Tine Verzeichnis zeigt?

Ich habe mir mal eine Ubuntu 18.04 VM aufgesetzt.

Da einmal Tine installiert via Repo und einmal manuell via tar ball.

Das Tinezeichen wird bei mir nur angezeigt, wenn ich bei der manuellen Instanz das DocumentRoot direkt auf das Tineverzeichnis zeigen lasse, in einem Unterordner geht es nicht, habe aber auch die Redirects nicht angepasst.

Bei der Repo-Installation wird mir das Tinezeichen nicht angezeigt, hier fehlen aber noch die Redirect in der Apache.conf von Tine, oder?

Viele Grüße
Uli

**Comment by pschuele** [comment]
> Bei der Repo-Installation wird mir das Tinezeichen nicht angezeigt, hier fehlen aber noch die Redirect in der Apache.conf von Tine, oder?

richtig, das kommt erst mit dem nächsten release. für ein subdir muss die rewrite rule in etwa so aussehen:

```apacheconf
<Location /tine20>
    RewriteCond %{REQUEST_FILENAME} -s [OR]
    RewriteCond %{REQUEST_FILENAME} -l [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^.*$ - [NC,L]
    RewriteRule ^.*$ index.php?doRouting=1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
</Location>

**Comment by pschuele** [comment]
it works now in the Ubuntu/Debian packages of version 2018.02.5!
