### ISSUE TITLE
Easily handle Contributor License Agreements

### ISSUE THREAD

**Issue by shochdoerfer** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#44]
In case you still require new contributors to sign a  Contributor License Agreement, you might want to have a look at [CLA assistant](https://cla-assistant.io) to automate the process here on GitHub.

**Comment by pschuele** [comment]
hi Stephan, thanks for the hint, we'll review that.

**Comment by pschuele** [comment]
cla assistant configured for this repo!

could anyone please check if it works?

**Comment by pschuele** [comment]
thanks :fireworks:
