### ISSUE TITLE
0008834:
sync failure: Syncroton_Command_Sync::getResponse::779 unable to convert entry to xml: No Permission.

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4441]
**Reported by jan on 25 Aug 2013 18:00**

**Version:** Kristina (2013.03.7)

Tine log flooded by error message:
sync failure: Syncroton_Command_Sync::getResponse::779 unable to convert entry to xml: No Permission.

**Additional information:** b1769 username - 2013-08-25T17:50:55+00:00 TRACE (8): Tinebase_Controller_Record_Abstract::checkFilterACL::1369 Setting filter grants for action sync
b1769 username - 2013-08-25T17:50:55+00:00 TRACE (8): Tinebase_Model_Filter_FilterGroup::getRequiredColumnsForSelect::793 Array
(
)

b1769 username - 2013-08-25T17:50:55+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_getSelect::702 Array
(
    [id] =&gt; tasks.id
)

b1769 username - 2013-08-25T17:50:55+00:00 TRACE (8): Tinebase_Model_Filter_Abstract::_getQuotedFieldName::308 Using tablename: tasks
b1769 username - 2013-08-25T17:50:55+00:00 TRACE (8): Tinebase_Model_Filter_Abstract::_getQuotedFieldName::308 Using tablename: tasks
b1769 username - 2013-08-25T17:50:55+00:00 TRACE (8): Tinebase_Model_Filter_Abstract::_getQuotedFieldName::308 Using tablename: tasks
b1769 username - 2013-08-25T17:50:55+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_fetch::660 SELECT `tasks`.`id` FROM `tine20_tasks` AS `tasks` WHERE (`tasks`.`is_deleted` = 0) AND ((`tasks`.`container_id` IN (&#039;366&#039;))) AND ((`tasks`.`last_modified_time` &gt; &#039;2013-02-12 14:32:54&#039;)) AND ((`tasks`.`last_modified_time` &lt; &#039;2013-08-25 17:50:55&#039;))
b1769 username - 2013-08-25T17:50:55+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::search::492 Fetched 61 ids.
b1769 username - 2013-08-25T17:50:55+00:00 DEBUG (7): ActiveSync_Controller_Abstract::getChangedEntries::466 Found 61 changed record(s).
b1769 username - 2013-08-25T17:50:55+00:00 INFO (6): Syncroton_Command_Sync::getResponse::648 found (added/changed/deleted) 62/0/0 entries for sync from server to client
b1769 username - 2013-08-25T17:50:55+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_getSelect::702 *
b1769 username - 2013-08-25T17:50:55+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_getSelect::702 *
b1769 username - 2013-08-25T17:50:55+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_getSelect::702 *
b1769 username - 2013-08-25T17:50:55+00:00 WARN (4): Syncroton_Command_Sync::getResponse::779 unable to convert entry to xml: No Permission.
b1769 username - 2013-08-25T17:50:55+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_getSelect::702 *
b1769 username - 2013-08-25T17:50:55+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_getSelect::702 *
b1769 username - 2013-08-25T17:50:55+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_getSelect::702 *
b1769 username - 2013-08-25T17:50:55+00:00 WARN (4): Syncroton_Command_Sync::getResponse::779 unable to convert entry to xml: No Permission.
b1769 username - 2013-08-25T17:50:55+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_getSelect::702 *
b1769 username - 2013-08-25T17:50:55+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_getSelect::702 *
b1769 username - 2013-08-25T17:50:55+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_getSelect::702 *
b1769 username - 2013-08-25T17:50:55+00:00 WARN (4): Syncroton_Command_Sync::getResponse::779 unable to convert entry to xml: No Permission.
b1769 username - 2013-08-25T17:50:55+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_getSelect::702 *
b1769 username - 2013-08-25T17:50:55+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_getSelect::702 *
b1769 username - 2013-08-25T17:50:55+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_getSelect::702 *
b1769 username - 2013-08-25T17:50:55+00:00 WARN (4): Syncroton_Command_Sync::getResponse::779 unable to convert entry to xml: No Permission.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 30 Aug 2013 11:16**

Please modify Syncroton/Command/sync.php ~ line 777

} catch (Exception $e) {
                        if ($this-&gt;_logger instanceof Zend_Log)
                            $this-&gt;_logger-&gt;warn(__METHOD__ . &#039;::&#039; . __LINE__ . &quot; unable to convert entry to xml: &quot; . $e-&gt;getTraceAsString());
                    }

Please reproduce the problem and send a new logile.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 30 Aug 2013 11:16**

and: please tell us, which tine version you are using.

**Comment by Gloirin** [comment]
**Comment posted by jan on 1 Sep 2013 19:12**

Sorry, tine version is 2013.03.7

660dd user - 2013-09-01T19:11:25+00:00 WARN (4): Syncroton_Command_Sync::getResponse::780 unable to convert entry to xml: #0 /var/www/tine20/Tinebase/Controller/Record/Abstract.php(319): Tinebase_Controller_Record_Abstract-&gt;_checkGrant(Object(Tasks_Model_Task), &#039;get&#039;)
#1 /var/www/tine20/ActiveSync/Controller/Abstract.php(293): Tinebase_Controller_Record_Abstract-&gt;get(&#039;1b9cd7932015d71...&#039;)
#2 /var/www/tine20/library/Syncroton/lib/Syncroton/Command/Sync.php(763): ActiveSync_Controller_Abstract-&gt;getEntry(Object(Syncroton_Model_SyncCollection), &#039;1b9cd7932015d71...&#039;)
#3 /var/www/tine20/library/Syncroton/lib/Syncroton/Server.php(145): Syncroton_Command_Sync-&gt;getResponse()
#4 /var/www/tine20/library/Syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#5 /var/www/tine20/ActiveSync/Server/Http.php(126): Syncroton_Server-&gt;handle()
#6 /var/www/tine20/Tinebase/Core.php(230): ActiveSync_Server_Http-&gt;handle()
#7 /var/www/tine20/index.php(17): Tinebase_Core::dispatchRequest()
#8 {main}

**Comment by Gloirin** [comment]
**Comment posted by jan on 9 Sep 2013 19:58**

Today I noticed that task filters (favorites) set for activesync devices are not working in our environment.
There are much more tasks synced to the device (galaxy s4 / android 4.2.2) as displayed in the tine web interface (with the same filter applied).
A not working activesync filter could be part of the problem.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Sep 2013 10:45**

@me: check if searching with &quot;sync&quot; grant and without &quot;read&quot; grant causes this error.

@jan: could you check the container grants for container id 366?

**Comment by Gloirin** [comment]
**Comment posted by jan on 11 Sep 2013 19:27**

id;container_id;account_type;account_id;account_grant
bfe20938adfb17870571310cac87268a8a80af56;366;anyone;0;exportGrant
bfe20938adfb17870571310cac87268a8a80af56;366;anyone;0;syncGrant
ceb400aeb39325220a2d20704fd8e4f030c2ed6e;366;user;1011;addGrant
ceb400aeb39325220a2d20704fd8e4f030c2ed6e;366;user;1011;adminGrant
ceb400aeb39325220a2d20704fd8e4f030c2ed6e;366;user;1011;deleteGrant
ceb400aeb39325220a2d20704fd8e4f030c2ed6e;366;user;1011;editGrant
ceb400aeb39325220a2d20704fd8e4f030c2ed6e;366;user;1011;exportGrant
ceb400aeb39325220a2d20704fd8e4f030c2ed6e;366;user;1011;readGrant
ceb400aeb39325220a2d20704fd8e4f030c2ed6e;366;user;1011;syncGrant
4750fd058e2e64053386da5e149e38b067d5cb62;366;user;1016;addGrant
4750fd058e2e64053386da5e149e38b067d5cb62;366;user;1016;deleteGrant
4750fd058e2e64053386da5e149e38b067d5cb62;366;user;1016;editGrant
4750fd058e2e64053386da5e149e38b067d5cb62;366;user;1016;exportGrant
4750fd058e2e64053386da5e149e38b067d5cb62;366;user;1016;readGrant
4750fd058e2e64053386da5e149e38b067d5cb62;366;user;1016;syncGrant

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 12 Sep 2013 09:53**

&gt; bfe20938adfb17870571310cac87268a8a80af56;366;anyone;0;syncGrant

ok, anyone has the syncGrant but no readGrant. that could be the problem!

**Comment by jan** [comment]
@Gloirin I've thought about it, but I have to refuse.

**Comment by pschuele** [comment]
@jan sorry for the spam - if you aren't the Jan who opened the issue in our mantis tracker :)

closing this issue - it's not longer relevant, I suppose.
