### ISSUE TITLE
Group memberships cached wrong in Redis

### ISSUE THREAD

**Issue by shochdoerfer** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#46]
Not exactly sure what caused this or where the problem actually comes from but we just had an issue where the cached group memberships in Redis were not correct. Deleting those records ("*getGroupMembershipsUSERID") from Redis and then logging out and back in again, fixed this.

Could also be a problem of the LDAP sync process that is running in our case. Since this happened out of the blue for the first time in a very long time, I am not sure what cause could be. Might also not be a problem related to Redis but a general problem in the caching layer.

**Comment by pschuele** [comment]
you can now download the fixed zf1 version here: https://github.com/tine20/zendframework1/releases/tag/1.12.20pl25

just unzip into tine20/vendor/zendframework/zendframework1

**Comment by shochdoerfer** [comment]
Are you sure this problem related to the zf1 Redis problem? We are using 2018.02.2 in prod where the error occured.

**Comment by pschuele** [comment]
it is not directlyrelated but the cache cleanup after the user sync is fixed in the current zf1 release, too.
