### ISSUE TITLE
Kein senden von Email über Active Sync

### ISSUE THREAD

**Issue by SvenPausH** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#47]
Hallo, ich habe Tine schon seit einigen Jahren installiert und immer mal ein Update gemacht.
Derzeit Version: 2018.02.

Tine nutze ich mit Android und Nine Client ebenfalls ohne Probleme.
Nun habe ich mir ein 2. Konto eingerichtet und genauso wie das 1. Konto in Nine eingerichtet.

Kalender, Aufgaben und Email Empfang funktioniert ohne Probleme.

Nun wollte ich vor ein paar Tagen auf eine Email Antworten und habe die Email nicht versendet bekommen.
Leider habe ich nur eine sehr oberflächliche Meldung bekommen (Email konnte ich versendet werden).
Eine eindeutige Fehlermeldung wäre mir natürlich lieber gewesen.
Das versehen von Emails über das 1. Konto funktioniert ohne Probleme.

Heute habe ich mir einmal alle Einstellungen in Tine und Nine angesehen und alles miteinander verglichen.
Ich habe keine Unterschiede gesehen.

Hat jemand eine Idee was ich noch überprüfen kann?
Habe ich in Tine noch vergessen ein Recht zu setzen?

Gruß

Sven

**Comment by pschuele** [comment]
hi Sven,

am besten, du wirst einen blick in das tine20 logfile (auf DEBUG). dort steht bestimmt drin, warum die mail nicht versendet werden konnte (vorausgesetzt, die email wurde überhaupt via activesync übertragen).

**Comment by SvenPausH** [comment]
Hallo, danke, Fehler gefunden.
Logfile lesen ja, wenn das nicht schon etwas peinlich ist. Hätte ich auch selbst mal drauf kommen können.
Ok zur Lösung:

Im Logfile habe ich folgendes gefunden:
.....CRIT (2): Syncroton_Server::_handlePost::166 exception message: no email address set for current user

Der Fehler war das ich im Benutzerkonto keine Emailadresse hinterlegt hatte.
Obwohl sonst im Webmailer alles funktioniert hat und auch alle anderen Dinge (Kalender, Aufgaben, Email) problemlos liefen, fiel der Fehler lange nicht auf.

**Comment by pschuele** [comment]
kein problem :)

dann mach ich den mal zu.
