### ISSUE TITLE
0000800:
Make more use of intellegent auto-completion

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#491]
**Reported by bbalazs on 7 Feb 2009 23:52**

**Version:** Lara (2009-02) Milestone 2

As a result of user-test: User would like to get more support by intelligent auto-completion. Consider this in every case, where there is a potentially limited number of possible results, e.g. Company-Name, City.

**Comment by pschuele** [comment]
duplicate of #289

**Comment by Gloirin** [comment]
Related to #4388
