### ISSUE TITLE
0000808:
Introduce concept "Belongs to"

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#495]
**Reported by bbalazs on 8 Feb 2009 00:39**

**Version:** Lara (2009-02) Milestone 2

As a  result of user-test: Users are confused by the fact that they cannot make one note on a person and a Lead at the same time. Or they wonder which Lead a certain Task belongs to.

So each element should get a section: &quot;Belongs to&quot;.

in this section for a contact could be shown, which task he works on, in which leads he is involved, etc. A Task could show, which people work in this task and which Lead it belongs to.

If notes can be attached to more than one object, notes could show, which people, task or leads they belong to.

**Comment by pschuele** [comment]
imho no longer relevant
