### ISSUE TITLE
Clear PHP version recommendation

### ISSUE THREAD

**Issue by tvannahl** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#52]
I am missing some clear recommendations in the whole tine enviroment. Maybe this could be easily addressed with the Github push. Since I found out about your move to github, I thought it would be easy to address those in multiple issues. Here is the first one:

**Recomended PHP Version**: This is something I would expect to see directly in the *README.md*, so I know that it gets updated because it is visible to everyone and not burried in a wiki or forum. Currently in the [wiki](https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/wiki/EN%3ASystem-requirements) I find PHP == 5.6  to be recommended but In your [forum](https://www.tine20.org/forum/viewtopic.php?f=12&t=18732&sid=082de5bdad6c99fc39d774e6e442c054) PHP 7.1 is recommeded.

Oh and the supported PHP versions would also be nice to see them documented.

**Comment by msphn** [comment]
5.6 is the minimum, 7.0+ is just faster.

**Comment by pschuele** [comment]
> Recomended PHP Version: This is something I would expect to see directly in the README.md, so I know that it gets updated because it is visible to everyone and not burried in a wiki or forum. Currently in the wiki I find PHP == 5.6 to be recommended but In your forum PHP 7.1 is recommeded.

feel free to create a pull request on the readme.md - you could add a chapter for recommended versions (PHP, MySQL/MariaDB, Redis, ...)

**Comment by msphn** [comment]
I updated the wiki requirements.
