### ISSUE TITLE
Archive(.org) old forum (https://www.tine20.org/forum/)

### ISSUE THREAD

**Issue by pschuele** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#54]
https://blog.archive.org/2017/01/25/see-something-save-something/

5. Sign up for an Archive-It Account

... and let archive.org crawl the whole site.

**Comment by msphn** [comment]
If someone wants it, someone should quickly take care of it. Board will shut of 25.5.!

**Comment by msphn** [comment]
Doesn't look like archive.org can crawl all pages at once. Not going to do this.

**Comment by pschuele** [comment]
no longer possible.
