### ISSUE TITLE
0010958:
Calendar sheet year view

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5423]
**Reported by pschuele on 2 Apr 2015 17:00**

Calendar sheet year view 

**Additional information:** needs a feature toggle

**Comment by Gloirin** [comment]
Related to #3955

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 2 Apr 2015 17:03**

change by Nico in the gerrit: https://gerrit.tine20.org/tine20/3061

I&#039;ll add a feature toggle to allow to switch this on/off.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Apr 2015 16:16**

change has been merged.

thx @Nico :)

**Comment by nico** [comment]
Anytime!
