### ISSUE TITLE
Repo Ubuntu 16.04

### ISSUE THREAD

**Issue by koelschejung74** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#63]
Hallo,

ich bekomme folgende Meldung bei apt upgrade:
E: Fehlschlag beim Holen von https://packages.tine20.org/ubuntu/pool/stable/t/tine20/tine20-humanresources_2018.02.4-1.1604_all.deb  404  Not Found

Dieses gilt für alle Pakete.

Ist die Unterstützung für Ubuntu 16.04 schon eingestellt? Wenn ich mir via Web das Repo anschaue, ist es heute noch aktualisiert worden oder habt Ihr das noch zurückgestellt, weil Euch noch was aufgefallen ist?

Viele Grüße
Uli

**Comment by pschuele** [comment]
hi Uli,

eigentlich stellen wir für die Community Edition nur noch für das aktuelle ubuntu (bzw. debian) lts pakete zur verfügung. mit dem gestrigen update sind wir auf 18.04 gegangen und haben die 16.04 pakete entfernt. in der Business Edition unterstützen wir auch noch ältere lts versionen.

prinzipiell laufen die 18.04 pakete auch mit 16.04 - man muss aber auf php7.2 (z.b. via ppa) gehen, damit die abhängigkeiten passen.

**Comment by pschuele** [comment]
andere möglichkeit ist die verwendung des tarballs - einfach in /usr/share/tine20 einspielen (z.b. via symlink)

**Comment by koelschejung74** [comment]
Hallo,

vielen Dank, dass die Unterstützung für Ubuntu 16.04 eingestellt wird, wurde ja schon im Forum kommuniziert. Das Vorgehen an sich verstehe ich komplett und kann ich nachvollziehen, nur den Zeitpunkt nicht.

Ubuntu bietet ein Upgrade bei einer LTS Version auf die nächste LTS Version erst an, wenn das erste Release, jetzt z. B. Ubuntu 18.04.1 raus ist, erst dann bekommt man die Meldung, dass eine neue Version zur Verfügung steht.

Wäre es nicht sinnvoll, sich daran zu orientieren? Viele, die Ubutnu im Einsatz haben, warten in der Regel bis diese Meldung raus kommt und so rel. "einfach" upzugraden.

Wenn man weiterhin tine über das Repo aktualisieren möchte, muss man nun entweder umsteigen auf manuelle Installation / Update über tar / zip, warten oder den Server, ich bezeichne es mal als hart upgraden. 

Bitte nicht als Kritik und Angriff empfinden, nur als keine Anregung.

Ihr macht super Arbeit.
Ich arbeite auch bei einer Firma, die OpenSource anbietet und kann daher auch Euren Standpunkt verstehen.

VG
Uli

**Comment by pschuele** [comment]
hi Uli,

danke für dein feedback. wir werden das auf jeden fall nochmal diskutieren.

> Ubuntu bietet ein Upgrade bei einer LTS Version auf die nächste LTS Version erst an, wenn das erste Release, jetzt z. B. Ubuntu 18.04.1 raus ist, erst dann bekommt man die Meldung, dass eine neue Version zur Verfügung steht.

das klingt auf jeden fall sinnvoll. vielleicht sollten wir uns daran orientieren.

melde mich, wenn es hier etwas neues gibt.
Philipp

**Comment by pschuele** [comment]
haben für das release 2018.02.5 nochmal pakete für 16.04 gebaut. vermutlich war das aber das letzte release für diese ubuntu version.

**Comment by koelschejung74** [comment]
Letzter Kommentar.
Super vielen Dank.

VG
Uli
