### ISSUE TITLE
Update 2018.02.2 to 2018.02.4 PHP Fatal error:  Uncaught Tinebase_Exception: waited for Action Queue to become empty for more than 300 sec

### ISSUE THREAD

**Issue by mgoppold** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#64]
Hi there,
the following Exception occurs during Update to 2018.02.4 with active redis:

```
PHP Fatal error:  Uncaught Tinebase_Exception: waited for Action Queue to become empty for more than 300 sec in /srv/www/vhosts/tine20.tbz-pariv.lan/Setup/Controller.php:692
Stack trace:
#0 /srv/www/vhosts/tine20.tbz-pariv.lan/Setup/Controller.php(576): Setup_Controller->_prepareUpdate(Object(Tinebase_Model_FullUser))
#1 /srv/www/vhosts/tine20.tbz-pariv.lan/Setup/Controller.php(476): Setup_Controller->updateApplication(Object(Tinebase_Model_Application), '11')
#2 /srv/www/vhosts/tine20.tbz-pariv.lan/Setup/Frontend/Cli.php(509): Setup_Controller->updateApplications(Object(Tinebase_Record_RecordSet))
#3 /srv/www/vhosts/tine20.tbz-pariv.lan/Setup/Frontend/Cli.php(465): Setup_Frontend_Cli->_updateApplications()
#4 /srv/www/vhosts/tine20.tbz-pariv.lan/Setup/Frontend/Cli.php(71): Setup_Frontend_Cli->_update(Object(Zend_Console_Getopt))
#5 /srv/www/vhosts/tine20.tbz-pariv.lan/Setup/Server/Cli.php(128): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#6 /srv/www/vhosts/tine20.tbz-pariv.lan/Setup/Core.php(115): Setup_Server_Cli in /srv/www/vhosts/tine20.tbz-pariv.lan/Setup/Controller.php on line 692
```
A second setup without redis updated successfully from 2018.02.2 to 2018.02.4

Distro: openSUSE42.3 x86_64 with:

- php7-7.0.7-37.2
- php7-redis-4.0.0-22.2
- redis-4.0.6-14.1
- apache2-2.4.23-22.1
- mysql-community-server-5.6.40-36.1

**Comment by koelschejung74** [comment]
Did you tried to update from 2018.02.2 -> 2018.02.03 -> 2018.02.04?

I used redis too.

* Ubuntu 16.04
* php 7.0.30
* php-redis 2.2.7-394
* redis-server :2:3.0.6-1
* mariadb-server 10.1.33

**Comment by mgoppold** [comment]
My Update was direct from 2018.02.2 to 2018.02.4 due to [issue 45](https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/issues/45):

In paulmhhs [comment from Apr 17](https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/issues/45#issuecomment-381777204):

...this version (2018.02.3) is broken with Redis as backend. It will not be fixed. The next version (2018.02.04) will work again...

**Comment by koelschejung74** [comment]
ok, sorry, but he used php 7.2, not 7.0. I didn't have this problem.

**Comment by paulmhh** [comment]
Previously a cache flush with Redis as cache backend would do a flushdb on the Redis. As sessions and ActionQueue use eventually the same Redis (default 0) db, that is a nono and has been fixed.

So either you have some artifacts in the Redis and you could use redis-cli to check and then flush the db and clear artifacts:
redis-cli keys '*TinebaseQueue*'
(if you get some data here, could get the data and post it here? redis-cli get KEY etc.)

to remove the artifacts:
redis-cli flushdb


or you are having still traffic (cron jobs?) on your installation that keep on pushing stuff to the ActionQueue. Stop the traffic and do the update then.

hope this helps to solve your issue

**Comment by mgoppold** [comment]
I currently have 188 entries:

```
# redis-cli keys '*TinebaseQueue*'
  1) "TinebaseQueueData:95e06da863656a61ae25eea63ae578383a27ca1d"
  2) "TinebaseQueueData:bacea96d3e5eace25c2d7c7613c666455dc3bf55"
  3) "TinebaseQueueData:837447cc011086f20de31ddd4dcb4ccb9994c7be"
..
186) "TinebaseQueueData:9f7a2805b02b45fa2665fb1d97511e714a564bc0"
187) "TinebaseQueueData:e9067e031f73fc5d8033a9e38de5b52109ff79ff"
188) "TinebaseQueueData:5df7cff893506c0369bb46749500bc810380a11f"
```
and

```
# redis-cli get "TinebaseQueueData:5df7cff893506c0369bb46749500bc810380a11f"
(error) WRONGTYPE Operation against a key holding the wrong kind of value
```

the contents for the last entry with dump:

```
# redis-cli dump "TinebaseQueueData:80b5fe0e9e53ea3716b452a602a6b16ffa5c86a6"
"\x04\x05\x05retry\xc0\x00\x04time\x132018-02-08 06:22:55\x04sha1(14a4b88198efea82f2eb3ffe6a8db014a0d4640e\x04data\xc3d\x1d\x80\x00\x00z\xb1\x1fa:3:{s:6:\"action\";s:31:\"Calendar\x01.s \x06\x0cEventNotifica@
......
\x007<\xf14\x1es\xf9L\xdd6y\x00}\x06status\ainQueue\b\x00g\x15\xe8\x0e\xd3\xc1>\x96"
```

In the last 10 minutes, the number of keys has not changed, I will try flushdb.

**Comment by mgoppold** [comment]
After ```redis-cli flushdb``` the update was successful, Thank you for your support.

FYE: During the update i run ```redis-cli --stat``` and there was no change.

**Comment by pschuele** [comment]
ok, thanks for the update. we'll keep an eye on this. but maybe your queue hasn't been processed because your worker had not been running?

**Comment by mgoppold** [comment]
possible, until recently I thought that the jobs will be started within the tine2.0, just like nextcloud does (aka webcron: cron.php every 15 minutes). The cron job `/usr/bin/php -d INCLUDEPATH tine20.php --method Tinebase.triggerAsyncEvents` was installed later.

If I run it now, no entries will be added to redis.

**Comment by paulmhh** [comment]
triggerAsyncEvents are sort of tine2.0 cronjobs, that is not the action queue

the action queue is a "near time" processing queue for long running jobs that may occur during normal tine2.0 operations. I guess you currently put jobs into the queue, but you don't have the queue worker running -> your jobs never get processed at all. The general advice is not to use the Redis backend for the action queue (but the default backend "direct", which means synchrounous, serial processing, basically it turns of the action queue).

If you feel confident in setting up a daemon (with monitoring and restarting etc.) then run the worker.php as a daemon. You'll have to read Tinebase_ActionQueue_Worker and Console_Daemon to understand how to set it up. There is no documentation

**Comment by pschuele** [comment]
if you are using the ubuntu/debian packages, you can install the tine20-worker package which sets up the worker demon and starts it automatically. if you are using a non-default redis-server setup, additional configuration might be necessary.

**Comment by dl5rcw** [comment]
same here on 2019.02.04 running debian 9, tine20 from source (no apt) and query using redis database. 
Apache 2.4 + php7.2 fpm, http2 enabled. using redis only for query. from 2019.02.04 we will use if for both query + sessions, b/c we recently experienced race conditions on file based sessions using tine20 + thunderbird with cardbook and tb-sync addon (investigation ongoing).

`redis-cli keys
redis-cli keys '*TinebaseQueue*'
redis-cli flushdb
/usr/bin/php -d INCLUDEPATH tine20.php --method Tinebase.triggerAsyncEvents
/usr/bin/php setup.php --update
`
worked for me.
