### ISSUE TITLE
0001124:
Layout on small screens

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#651]
**Reported by Olodin on 28 Jun 2009 18:33**

**Version:** Leonie (2009-07) Beta 1

I noticed lots of scrollbars in Firefox 3.0 on a 1024x768 screen in the adressbook. When the contact preview at the bottom is on (as it is per default) there are two vertical and one horizontal scrollbars (marked with the red arrows). 
Enlarging the contact preview a bit vertically would get rid at least for the bottom right scrollbar at this resolution.

I&#039;ve also marked lots of free space blue. The idea is to move the user and online info at the top bar where the preferences and logout button is located. This would gain some more space for data in all tine20 applications.

**Additional information:** See:
http://www.tine20.org/forum/viewtopic.php?f=18&amp;t=676

**Comment by pschuele** [comment]
already implemented with the changes for touch devices.

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 1 Jul 2009 17:04**

Just noticed that those scrollbars are also there at resolution of 1280x1024. Maybe it&#039;s a 4:3 layout problem?

**Comment by Gloirin** [comment]
**Comment posted by phsc on 1 Jul 2009 20:24**

I don&#039;t think, that it&#039;s a 4:3 layout problem, because I have no scrollbars on my 1400x1050 screen (see attached screenshot).

Edit:
My Browser is Firefox 3.5.

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 7 Jul 2009 07:09**

Ok, seems to just a problem with the screen width. Have the same scrollbars at 1280x800 on Firefox 3.0.
