### ISSUE TITLE
Export Adressbuch in Excel funktioniert nicht

### ISSUE THREAD

**Issue by miwi0** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#67]
Ich versuche das Adressbuch zu Exportiere "Kontakte -> Excel - alle Daten" zu exportieren -> keine Reaktion auf Interface-Seite. 
Debug Eintrag: Tinebase_Export_Xls::_createDocument::201 could not copy template file to temp path
Im temp-Verzeichnis erscheint eine leere Datei
Danke

**Comment by paulmhh** [comment]
please use English.

which version is currently installed?

please check the importexport_definition table for the row with `name = "adb_xls"` the column plugin_options should contain a XML having a tag like this:
`<template>tine20:///Tinebase/folders/shared/export/templates/Addressbook/addressbook_contact_export.xlsx</template>`
you can use WebDAV to access the path (replace `tin20://` with the right url) and check if the template is readable. Somewhere along that line of actions something should go wrong.

**Comment by paulmhh** [comment]
actually you have to remove the '/folders' part of the url too, so the url would look something like:

`.../webdav/Tinebase/shared/export/templates/Addressbook/addressbook_contact_export.xlsx`

**Comment by miwi0** [comment]
I have access via WebDAV to
`.../webdav/Tinebase/shared/export/templates/Addressbook/addressbook_contact_export.xlsx`
I'm confused about the export definition:
* I found in the database
* I found a folder `/usr/share/tine20/Addressbook/Export/definitions`

Could you please roughly explain, how tine20 includes the import/export filters.
I use tine20 for several major releases, is there somewere a sql expression that rewrites the table `importexport_definition`

**Comment by paulmhh** [comment]
from
`<template>tine20:///Tinebase/folders/shared/export/templates/Addressbook/addressbook_contact_export.xlsx</template>`
to
`<template>tine20:///Tinebase/shared/export/templates/Addressbook/addressbook_contact_export.xlsx</template>`

these are the same paths.

I would not change anything in the XML files. Use the XML files that come with your current version.

doing --updateAllImportExportDefinitions will reset your database to the state of the XML files. That should solve your problem. I close this with the resolution: use --updateAllImportExportDefinitions
