### ISSUE TITLE
0013562:
Error Kontaktsuche im Kalender

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6708]
**Reported by dl6mra on 18 Oct 2017 08:49**

**Version:** 2017.08.5 Community Edition

SQLSTATE[HY000]: General error: 1191 Can&#039;t find FULLTEXT index matching the column list, query was: SELECT `addressbook`.`id`, `addressbook`.`n_fileas`, `accounts`.`id` AS `account_id` FROM `tine20_addressbook` AS `addressbook` LEFT JOIN `tine20_accounts` AS `accounts` ON `addressbook`.`id` = `accounts`.`contact_id` WHERE (`addressbook`.`is_deleted` = 0) AND ((((`addressbook`.`container_id` IN (&#039;10&#039;))))) AND (((((`addressbook`.`n_family` LIKE (&#039;%teest%&#039;))) OR ((`addressbook`.`n_given` LIKE (&#039;%teest%&#039;))) OR ((`addressbook`.`org_name` LIKE (&#039;%teest%&#039;))) OR ((`addressbook`.`org_unit` LIKE (&#039;%teest%&#039;))) OR ((`addressbook`.`email` LIKE (&#039;%teest%&#039;))) OR ((`addressbook`.`email_home` LIKE (&#039;%teest%&#039;))) OR ((`addressbook`.`adr_one_locality` LIKE (&#039;%teest%&#039;))) OR ((MATCH (`addressbook`.`note`) AGAINST (&#039;+teest*&#039; IN BOOLEAN MODE)))))) AND ((`addressbook`.`container_id` IN (&#039;1&#039;, &#039;10&#039;, &#039;101&#039;, &#039;156&#039;, &#039;308&#039;, &#039;392&#039;, &#039;393&#039;, &#039;394&#039;))) AND ((/* is no user */ `accounts`.`id` IS NULL OR /* is user */ (`accounts`.`id` IS NOT NULL AND `accounts`.`status` != &#039;disabled&#039; AND (`accounts`.`visibility` = &#039;displayed&#039; OR `accounts`.`id` = &#039;746392b6e5e84aeb1d91df0a768ffd4419e5b99b&#039;)))) GROUP BY `addressbook`.`id` ORDER BY `n_fileas` ASC LIMIT 50

.../vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo-&gt;_execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement-&gt;execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query()
.../Tinebase/Backend/Sql/Abstract.php(762): Zend_Db_Adapter_Pdo_Abstract-&gt;query()
.../Tinebase/Backend/Sql/Abstract.php(551): Tinebase_Backend_Sql_Abstract-&gt;_fetch()
.../Tinebase/Controller/Record/Abstract.php(219): Tinebase_Backend_Sql_Abstract-&gt;search()
.../Tinebase/Frontend/Json/Abstract.php(205): Tinebase_Controller_Record_Abstract-&gt;search()
.../Addressbook/Frontend/Json.php(90): Tinebase_Frontend_Json_Abstract-&gt;_search()
[internal function]: Addressbook_Frontend_Json-&gt;searchContacts()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): call_user_func_array()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract-&gt;_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
.../Tinebase/Server/Json.php(336): Zend_Json_Server-&gt;handle()
.../Tinebase/Server/Json.php(171): Tinebase_Server_Json-&gt;_handle()
.../Tinebase/Core.php(237): Tinebase_Server_Json-&gt;handle()
.../index.php(18): Tinebase_Core::dispatchRequest()

**Comment by Gloirin** [comment]
**Comment posted by dl6mra on 18 Oct 2017 08:53**

Sorry, im Adressbuch nicht Kalender

**Comment by Gloirin** [comment]
**Comment posted by dl6mra on 18 Oct 2017 09:45**

Its works after &quot;tine20.php --method=Tinebase.upgradeMysql564&quot;

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Oct 2017 12:05**

ok, great. thanks for the update.

**Comment by xp81user** [comment]
Hi,
i have a short question. is there a similar way for the CRM Module? because i have this error in the search-function of CRM. In all the other application everthing works fine. 
Thanks

**Comment by pschuele** [comment]
```
tine20.php --method=Tinebase.upgradeMysql564
```

should help here, too.
