### ISSUE TITLE
0013866:
Update Tine20 to 2018.02.5

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6857]
**Reported by bernhard on 4 Jun 2018 12:48**

**Version:** git master

Beim Update kommt filgende Fehlermeldung:

PHP Fatal error:  Uncaught exception &#039;PDOException&#039; with message &#039;SQLSTATE[42S02                                                                                                                                   ]: Base table or view not found: 1146 Table &#039;tine20.tine20_application_states&#039; d                                                                                                                                   oesn&#039;t exist&#039; in /var/www/html/tine20/vendor/zendframework/zendframework1/librar                                                                                                                                   y/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/html/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Stat                                                                                                                                   ement/Pdo.php(228): PDOStatement-&gt;execute(Array)
#1 /var/www/html/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Stat                                                                                                                                   ement.php(303): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#2 /var/www/html/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adap                                                                                                                                   ter/Abstract.php(480): Zend_Db_Statement-&gt;execute(Array)
#3 /var/www/html/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adap                                                                                                                                   ter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(Object(Zend_Db_Select                                                                                                                                   ), Array)
#4 /var/www/html/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Sele                                                                                                                                   ct.php(711): Zend_Db_Adapter_Pdo_Abstract-&gt;query(Object(Zend_Db_Select))
#5 /var/www/html/tine20/Tinebase/ in /var/www/html/tine20/vendor/zendframework/z                                                                                                                                   endframework1/library/Zend/Db/Statement/Pdo.php on line 235

Fatal error: Uncaught exception &#039;PDOException&#039; with message &#039;SQLSTATE[42S02]: Ba                                                                                                                                   se table or view not found: 1146 Table &#039;tine20.tine20_application_states&#039; doesn&#039;                                                                                                                                   t exist&#039; in /var/www/html/tine20/vendor/zendframework/zendframework1/library/Zen                                                                                                                                   d/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/html/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Stat                                                                                                                                   ement/Pdo.php(228): PDOStatement-&gt;execute(Array)
#1 /var/www/html/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Stat                                                                                                                                   ement.php(303): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#2 /var/www/html/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adap                                                                                                                                   ter/Abstract.php(480): Zend_Db_Statement-&gt;execute(Array)
#3 /var/www/html/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adap                                                                                                                                   ter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(Object(Zend_Db_Select                                                                                                                                   ), Array)
#4 /var/www/html/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Sele                                                                                                                                   ct.php(711): Zend_Db_Adapter_Pdo_Abstract-&gt;query(Object(Zend_Db_Select))
#5 /var/www/html/tine20/Tinebase/ in /var/www/html/tine20/vendor/zendframework/z                                                                                                                                   endframework1/library/Zend/Db/Statement/Pdo.php on line 235

Die Tabelle tine20.tine20_application_states gibt es auch in der Datenbank nicht!

**Additional information:** CentOS 7, apache 2.4.6, php 5.6

**Comment by pschuele** [comment]
fixed in 2018.02.6 - see #77 and others
