### ISSUE TITLE
upgrade 2018.02.02 -> 2018.02.04 theme broken

### ISSUE THREAD

**Issue by ravermeister** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#71]
Hi, after the Upgrade my theme is broken, I see a mixed blue and gray theme...
below is the Config entry:
```
  'theme' =>
  array (
    'active' => true,
    'path' => 'xtheme-rimkus-gray',
    'useBlueAsBase' => false,
  ),
```
in 2018.02.02 everything was fine...
and the tine log is empty. 
log level is: 
```
  'logger' =>
  array (
    'active' => true,
    'filename' => '/home/raver/logs/tine.log',
    'priority' => 3,
  ),
```

**Comment by pschuele** [comment]
we are working on a new general theme but won't add support for custom themes in the near future.
