### ISSUE TITLE
CRM andere Nutzer werden nicht gelistet

### ISSUE THREAD

**Issue by Peter-Frankenfeldt** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#72]
Ausgangslage
Tin20 v2017.08.11
- Das CRM-Modul wurde intensiv von Nutzer A genutzt und funktionierte einwandfrei.
- Liste der Leads von Nutzer A waren freigegeben für Nutzer B, alles OK

Update auf Tine20 v2018.02.1 -> Tine20 v2018.02.2
- Im CRM-Modul werden keine Einträge für Benutzer A mehr gelistet, permanentes Sync-Icon.
- Im CRM-Modul sieht Nutzer B keine Einträge von Nutzer A, permanentes Sync-Icon.
- Test mit 2. Benutzer C und D, neue Einträge angelegt und freigegeben. Nutzer D kann die neuen 
Einträge von Nutzer C aber nicht von Nutzer A einsehen.

Update auf Tine20 v2018.02.3
- Nutzer A sieht seine Einträge.
- Nutzer B kann nicht auf die Liste von Nutzer A zugreifen, permanentes Sync-Icon.

**Tests & Auffälligkeiten:**
Limitieren der Anzahl der angezeigten Leads durch einschränken des Zeitraumes.
-> Filter: Alles zeigen was vor YYYY-MM-DD erstellt wurde.
-->	Funktioniert bis Datum heute – 1 Jahr ist.

-> Filter: Alles zeigen was in einer bestimmten Woche erstellt wurde.
-->	Funktioniert teilweise, auch im Zeitraum des letzten Jahres. 

-> Filter: Alles zeigen, was an einem bestimmten Tag erstellt wurde.
--> Funktioniert teilweise, auch im Zeitraum des letzten Jahres.
--> Hier lässt sich das Problem auf einzelne Leads eingrenzen. Einige verhindern das Auflisten, andere werden ohne Probleme geladen.
--> Ein Vergleich der DB-Einträge für zweier Leads ergab keinen Unterschied, auf den das Problem zurückzuführen ist.
--> Eine Kopie (als DB-Eintrag) blockierender Leads in ein Testsystem ergab kein blockierendes Verhalten.

**Comment by pschuele** [comment]
in 2018.02.2 gab es definitiv ein problem mit dem CRM.
wie ist denn das verhalten in der ganz neuen 2018.02.5 version?

> --> Hier lässt sich das Problem auf einzelne Leads eingrenzen. Einige verhindern das Auflisten, andere werden ohne Probleme geladen.
--> Ein Vergleich der DB-Einträge für zweier Leads ergab keinen Unterschied, auf den das Problem zurückzuführen ist.

vielleicht steht etwas im logfile (DEBUG level)? es lohnt sich oft, dort einen blick herein zu werfen, da hier fehlerursachen schnell sichtbar werden.

**Comment by Peter-Frankenfeldt** [comment]
Version 2018.02.5 auf Testsystem installiert und alles funktioniert.
Live-System wird noch geprüft. 
Danke.

**Comment by pschuele** [comment]
> Version 2018.02.5 auf Testsystem installiert und alles funktioniert.

topp. einfach wieder melden, wenn es noch probleme gibt. ich schliesse das derweil.
