### ISSUE TITLE
0001366:
STRG-A is not working in edit dialogs

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#770]
**Reported by pschuele on 27 Jul 2009 09:05**

**Version:** Leonie (2009-07) Beta 3

STRG-A is not working in edit dialogs

**Additional information:** see http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=894

**Comment by pschuele** [comment]
imho no longer relevant
