### ISSUE TITLE
0001420:
After renaming a user in the admin panel, the user's name doesn't change inside the account

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#797]
**Reported by awieland on 7 Aug 2009 09:04**

**Version:** Leonie (2009-07) RC 1

As admin, I changed the name and surname of a user. After this user logged into her account, the old name could still be found on several places like the personal containers (&quot;...&#039;s personal calendar&quot;, &quot;...&#039;s personal addressbook&quot;, etc.), on the bar at the bottom (&quot;User: ...,...&quot;) and when creating an appointment (as accepted Attendee) or timesheet (under &quot;Account&quot;).

**Comment by pschuele** [comment]
already fixed
