### ISSUE TITLE
What is Major or Minor Package

### ISSUE THREAD

**Issue by landei16** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#82]
Hi All,

have a very old installation running (2015.07.7) but upgrade fails with this message:

'Major version jumps are not allowed. Upgrade your current major Version to the most recent minor Version, then upgrade to the most recent next major version. Repeat until you reached the desired major version you want to upgrade to"

Problem is that it´s not possible to download the respective versions here on official github.

Is there any chance to upgrade these old version but a re installation?

Best regards and thanks
Landei16

**Comment by paulmhh** [comment]
The versions are all tagged on github:
https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/tree/2016.03.1

2016.03.1 -> 2016.03.5 -> 2016.09.1 -> 2016.09.7 -> etc.

**Comment by landei16** [comment]
Found all the necessary stuff and could upgrade to 2017.8.1
Thanks for the help...
