### ISSUE TITLE
0001472:
Permission management: needs rethinking

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#823]
**Reported by awieland on 11 Aug 2009 13:32**

**Version:** Leonie (2009-07-1)

* some rights are not clear what they mean (why is there a distinction between Add and Edit?)
* When granted a higher permission, that includes one or more of the others, these should be checked and greyed out (for example when granted the Edit permission, Read and Add should automatically be checked and greyed out)

**Comment by pschuele** [comment]
imho no longer relevant
