### ISSUE TITLE
0001476:
Addressbook entry needs better company management

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#825]
**Reported by csak on 11 Aug 2009 13:37**

As there are more people in any calendar from the same company it is a problem that the company 
- cannot be selected from a list
- it&#039;s address must be typed in for all entries
- the addresses are not kept in sync.

This results in inconsistent data for even a small install like ours (&lt;100 contacts, yet)

**Comment by pschuele** [comment]
duplicate of #355

**Comment by Gloirin** [comment]
Related to #2512
