### ISSUE TITLE
0001486:
Mini calendar on the left: write days bold that have appointments

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#830]
**Reported by awieland on 11 Aug 2009 14:25**

**Version:** Leonie (2009-07-1)

Instead, for days that are shown on the right, the light blue background is enough.

**Comment by pschuele** [comment]
imho no longer relevant

**Comment by Gloirin** [comment]
**Comment posted by ravermeister on 13 Oct 2014 08:01**

but please use css classes instead of hard coded css or colors,
so that other themes can configure it to fit into the theme.
