### ISSUE TITLE
0001506:
Users should have the right to edit/update their own data in the internal contacts folder

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#840]
**Reported by rokka on 12 Aug 2009 16:32**

**Version:** Leonie (2009-07-1)

It would be a great feature if users could edit their own data. Maybe this option could be allowed or denied by the administrator.

**Comment by pschuele** [comment]
already implemented

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 13 Apr 2010 19:09**

should not be active by default, in my environment the data is set via external scripts ...
