### ISSUE TITLE
German sidebar translated

### ISSUE THREAD

**Issue by tvannahl** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#86]
Just a note, since I am currently looking into the wiki. Wouldn't it be better if the german menu of the wiki actually is in german?

The following patch could fix that:

```
From 07bdf850dfabf60f061d1b5012c949aa5315d042 Mon Sep 17 00:00:00 2001
From: Theodor van Nahl <theo_dev@van-nahl.org>
Date: Wed, 6 Jun 2018 14:54:01 +0200
Subject: [PATCH] German sitebar translated.

The wiki sitebar has been adjusted to give german speaking users a more
welcomeing feel.
---
 _Sidebar.md | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)

diff --git a/_Sidebar.md b/_Sidebar.md
index d043e3f..e3e61d4 100644
--- a/_Sidebar.md
+++ b/_Sidebar.md
@@ -1,9 +1,9 @@
-- [[German|DE:Home]]
-    - [[System requirements|DE:System requirements]]
-    - [[Install Howto|DE: Install Howto]]
+- [[Deutsch|DE:Home]]
+    - [[System Anforderungen|DE:System requirements]]
+    - [[Installations Howto|DE: Install Howto]]
     - [[Update Howto|DE:Update Howto]]
     - [[FAQ|DE:FAQ]]
-    - [[Migrating Postgres-->MySQL|DE:Migration von Postgres nach MySQL]]
+    - [[Migration Postgres-->MySQL|DE:Migration von Postgres nach MySQL]]
 
 - [[English|EN:Home]]
     - [[System requirements|EN:System requirements]]
-- 
2.17.0
```

**Comment by pschuele** [comment]
thanks! why don't you change it directly in the wiki? is there a permission problem?

**Comment by tvannahl** [comment]
Doing that online would probably work, but I do like to have a Diff before commit and I do like to make semantic commits. Furthermore if I make some structural changes I would love to have those reviewed and discussed, if nessesary.

To bad that Github doesn't support pull requests to Wikis directly. The only workflow that comes into my mind in that regards would be to have a extra repository that gets pushed into **Tine-2.0-Open-Source-Groupware-and-CRM.wiki**. To put my 2 ¢ worth.

**Comment by pschuele** [comment]
yup, we also hoped for a pull request workflow in the github wiki. we'll discuss your idea with the extra repo which is replicated into the wiki repo.
but as long as we don't have that, please work in the wiki directly - we'll check that from time to time ;)

**Comment by pschuele** [comment]
here's my review for the change: +1
:smile:

**Comment by tvannahl** [comment]
Thanks for the feedback. Job done :-)

**Comment by pschuele** [comment]
great, thanks for that :smiley:
