### ISSUE TITLE
0001586:
Category to Calendar mapping

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#880]
**Reported by scarre on 27 Aug 2009 09:37**

It would be useful to be able to define a Category (on the mobile device) to Calendar (in Tine20) mapping so that, upon syncing:
1) events created on a mobile device with a defined category end up in the corresponding calendar in Tine
2) events created in a specific calendar in Tine end up in the corresponding category on the mobile device

**Comment by Gloirin** [comment]
**Comment posted by konus on 10 May 2011 14:19**

It should be specified, which mobile devices support categories on calendar. HP/Palm with WebOS 2.1 does not. But it is possible to sync several calendars on the device to several on tine.

**Comment by pschuele** [comment]
don't think that this is still relevant as the major mobile OSes now support multiple calendars
