### ISSUE TITLE
0001636:
Agenda View for Calendar

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#902]
**Reported by js on 11 Sep 2009 14:34**

**Version:** Leonie (2009-07-4)

An Agenda View for Calendar. Best configureable how many days/Appointments should be displayed

**Comment by pschuele** [comment]
already implemented

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 14 Jan 2011 09:56**

here is a screenshot how this could look like: http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=5158

**Comment by Gloirin** [comment]
**Comment posted by holgerb on 3 Sep 2013 13:41**

As this is getting postponed ever since 2009, probably as the solution planned is a &quot;deluxe&quot; version that is a lot of work to implement, I suggest a very simple solution that might help some of us who want to search throughout the calendar.

Why not add an additional button in listview only that removes the date restriction? There you would have &quot;day&quot;, &quot;week&quot;, &quot;month&quot; and &quot;all&quot;. Where &quot;all&quot; displays all records present in the selected calendar view (pages of course). Now you can at least search through all entries.

What do you think?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Sep 2013 18:50**

what about recurring events? should they be removed from the result list? because if not, there might be infinite events in the result set.

maybe we should move this to a new feature request as it does not exactly represents the agenda view.

**Comment by Gloirin** [comment]
**Comment posted by holgerb on 11 Sep 2013 20:39**

Hi Philipp,

yes you are right, I&#039;m going to start a new ticket. The ID is 8902

https://forge.tine20.org/mantisbt/view.php?id=8902

Good point with the recurring events. I posted a suggestion in the new ticket.

Holger

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 12 Sep 2013 09:54**

hi Holger,

thanks for that :)
