### ISSUE TITLE
0001652:
Letzte Aufgabe in Taskliste verschwindet hinter unterer Statusleiste

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#910]
**Reported by RolWg on 14 Sep 2009 13:53**

**Version:** Leonie (2009-07-5)

Dieser Bug ist unabhängig von der Anzahl der eingegebenen Tasks.

**Comment by pschuele** [comment]
imho no longer relevant
