### ISSUE TITLE
CalenderSync with Thunderbird

### ISSUE THREAD

**Issue by koelschejung74** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#94]
Hello,

i updated to the new Version 02.06. After that the calender-syc works only with debug -level 7. If it setup it to 5, no sync, after changing to 7 it works.

Is this correct? Or where is my fault?

kind regards

**Comment by pschuele** [comment]
that seems to be a bug - I'll have a look.
as this is a duplicate of #96, I'm closing it.
