### ISSUE TITLE
I found a deprecated message in logfile

### ISSUE THREAD

**Issue by koelschejung74** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#95]
I found the following Meesage in Logfile:

DEBUG (7): Tinebase_Container::_resolveRecordClassArgument::400 Using application name is deprecated. Please use the classname of the model or the class itself

What wrong here?

I used Ubuntu 16.04 with php 7.0

**Comment by pschuele** [comment]
nothing serious - this DEBUG log can be ignored. it's just a reminder for the developers to clean that up sometimes :)
