### ISSUE TITLE
0001740:
don't add tag as new if it has same name and context of an existing tag

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#954]
**Reported by pschuele on 2 Oct 2009 09:01**

don&#039;t add tag as new if it has same name and context of an existing tag

- just attach the existing tag

**Additional information:** http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=1322

**Comment by pschuele** [comment]
imho no longer relevant
